wrtnlabs/agentica

README.md
test/features/resolve.ts

This pull request includes several changes to the `README.md` file and a new addition to `test/features/resolve.ts`. The most important changes include correcting a function call, updating links in the components comparison table, and adding a new function to the test file.
Updates to `README.md`:
* Corrected the function call in the `correctFunctionCall` function to use parentheses around the arrow function parameter.
* Updated links in the components comparison table to point to the correct files for "Array (repeated, union)" and "Ultimate Union Type".
New addition to `test/features/resolve.ts`:
* Added a new `sum` function that returns a promise resolving to the sum of two numbers and exported a constant `is` using this function.

Fix README DTO bebchmark links

---

README.md
package.json
src/module.ts
src/rpc/IWrtnAgentRpcListener.ts
src/rpc/IWrtnAgentRpcService.ts
src/rpc/WrtnAgentRpcService.ts
test/examples/websocket.client.ts
test/examples/websocket.server.ts
test/features/resolve.ts

This pull request introduces WebSocket communication capabilities to the `@wrtnlabs/agent` package, updates the package version, and adds new RPC-related modules. The most important changes include the addition of WebSocket communication examples, updates to the `package.json` file, and the creation of new RPC service and listener interfaces.
* Added a section in `README.md` explaining how to use the WebSocket interaction module provided by `@wrtnlabs/agent`, including code examples for both backend server and frontend application development.
* Updated the package version in `package.json` from `0.1.0` to `0.2.0`.
* Added `tgrid` as a new dependency in `package.json`.
* Added new RPC-related modules to the `src` directory, including `IWrtnAgentRpcListener`, `IWrtnAgentRpcService`, and …

Add websocket interaction module

---

packages/agent/package.json
packages/agent/test/features/test_base_event.ts
packages/agent/test/features/test_base_websocket.ts
packages/agent/test/features/test_base_work.ts
packages/agent/test/features/test_benchmark_call.ts
packages/agent/test/features/test_benchmark_predicator.ts
packages/agent/test/features/test_benchmark_predicator_simple_allof.ts
packages/agent/test/features/test_benchmark_select.ts
packages/agent/test/index.ts

This pull request includes several changes to the `packages/agent` module, primarily focusing on updating dependencies and improving the test suite by handling missing API keys more gracefully. The most important changes include updating the `@nestia/e2e` dependency version, modifying test functions to check for the presence of `CHATGPT_API_KEY`, and removing the OpenAI import in some test files.
* [`packages/agent/package.json`](diffhunk://#diff-f0f4adde46deb8e106c88cfb5dbf48155b8261ff0d73ada3429381a40e9bb3baL49-R49): Updated `@nestia/e2e` dependency from version `^0.8.0` to `^0.8.2`.
* [`packages/agent/test/features/test_base_event.ts`](diffhunk://#diff-7ce7c8826565128d36a365860f016aa1010ed7ab28976f97ef5b0a2da1d61072L4-R8): Modified `test_base_event` function to check for …

Do not test LLM token required feature on Github Actions

---

README.md
package.json
packages/core/src/internal/AgenticaTokenUsageAggregator.ts
packages/core/src/structures/IAgenticaTokenUsage.ts

This pull request includes various updates to the `agentica` project, focusing on improving documentation, updating package versions, and renaming properties for clarity. The most significant changes are summarized below:
Documentation Improvements:
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L9-L35): Enhanced the description of the `agentica` library for better clarity and readability, including a more concise explanation of its capabilities and a simplified code example.
Version Updates:
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L4-R4): Updated the version of the `@agentica/station` package from `0.8.0` to `0.8.1`.
Property Renaming for Clarity:
* …

Concise README, and change `IAgenticaTokenUsage`

---

packages/core/src/structures/IAgenticaProvider.ts

example: https://openrouter.ai/google/gemini-2.0-flash-lite-001/api
Sometimes you use the open ai form as an API gateway.
So we will be not going to limit the model to Chatgpt
Format must be limited to chatgpt.

feat: Agnetica should support third party cloud hosting

---

README.md
articles/new-backend-development-paradigm-in-the-new-ai-era.md
package.json
packages/benchmark/README.md
packages/benchmark/src/internal/AgenticaBenchmarkPredicator.ts
packages/core/README.md
packages/core/src/Agentica.ts
packages/core/src/index.ts
packages/core/src/structures/IAgenticaContext.ts
packages/core/src/structures/IAgenticaEvent.ts
packages/core/src/structures/IAgenticaProps.ts
packages/core/src/structures/IAgenticaTokenUsage.ts
packages/core/src/structures/IAgenticaVendor.ts
test/src/cli.ts
test/src/features/test_base_event.ts
test/src/features/test_base_websocket.ts
test/src/features/test_base_work.ts
test/src/features/test_benchmark_call.ts
test/src/features/test_benchmark_predicator.ts
test/src/features/test_benchmark_predicator_simple_allof.ts
test/src/features/test_benchmark_select.ts

To avoid the same word confusing between LLM provider and function providing, I've separated them to vendor and controller.
---------------
This pull request includes several changes across multiple files to update terminology from "provider" to "vendor" and to update the version number in `package.json`. The most important changes are summarized below:
Terminology Update:
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L20-R20): Changed `provider` to `vendor` in the `Agentica` initialization.
* [`articles/new-backend-development-paradigm-in-the-new-ai-era.md`](diffhunk://#diff-c353bd6ccba7821dbb937f8c53d8cd1197819fb5a10edd09c682ece233a2b71dL62-R62): Changed `provider` to `vendor` in multiple instances to reflect the new terminology. …

LLM service provider becomes vendor.

---

packages/core/README.md
packages/core/src/chatgpt/ChatGptCallFunctionAgent.ts
packages/core/src/structures/IAgenticaController.ts
packages/core/src/structures/IAgenticaOperation.ts
packages/core/src/structures/IAgenticaOperationSelection.ts
packages/core/src/structures/IAgenticaPrompt.ts

This pull request focuses on simplifying the codebase by replacing the `ILlmFunctionOfValidate` and `ILlmApplicationOfValidate` types with `ILlmFunction` and `ILlmApplication` respectively across multiple files in the `packages/core` directory. The changes aim to streamline the type definitions and improve code readability.
The most important changes include:
* [`packages/core/README.md`](diffhunk://#diff-af0c08d6f291aa75c55d4ad3ec19fd4b728edcf43a39c80d566f661b3b311c44L182-R182): Replaced `ILlmFunctionOfValidate` with `ILlmFunction` and `ILlmApplicationOfValidate` with `ILlmApplication` in various code examples and documentation references. [[1]](diffhunk://#diff-af0c08d6f291aa75c55d4ad3ec19fd4b728edcf43a39c80d566f661b3b311c44L182-R182) …

Utilize `IHttpLlmFunction.validate()` function

---

website/app/layout.jsx

Yellow to white(254,252,232 -> 250,250,250)
before:
after:
maybe you follow [generated code](https://nextra.site/docs/blog-theme/start#:~:text=%3CHead%20backgroundColor%3D%7B%7B%20dark%3A%20%27%230f172a%27%2C%20light%3A%20%27%23fefce8%27%20%7D%7D%20/%3E), but nextra page use [250,250,250](https://nextra.site/docs/blog-theme/start)

fix: Change the document's light theme background color to white

---

package.json
packages/core/src/context/internal/AgenticaTokenUsageAggregator.ts
packages/rpc/src/AgenticaRpcService.ts
packages/rpc/src/IAgenticaRpcListener.ts
packages/rpc/src/IAgenticaRpcService.ts
test/src/features/test_base_websocket.ts

This pull request includes several changes aimed at improving the codebase by removing the use of the `Primitive` type from `typia` and making minor version updates. The most important changes include modifications to the `AgenticaRpcService`, `IAgenticaRpcListener`, and `IAgenticaRpcService` interfaces, as well as updates to the `test_base_websocket` function.
* [`packages/core/src/context/internal/AgenticaTokenUsageAggregator.ts`](diffhunk://#diff-80f3483e6d925b278ef4d4097e99578defcb2f9ccad718d5caebe1a530c46bdbL2-R8): Replaced `Primitive<AgenticaTokenUsage>` with `IAgenticaTokenUsageJson` in the `aggregate` method.
* [`packages/rpc/src/AgenticaRpcService.ts`](diffhunk://#diff-ff117542d38be6a7963841ec4b486914ee24ac26cbc15c123525060a9ea084edL95-R96): Removed `Primitive` type from the …

Fix websocket problem

---

website/content/docs/concepts/function-calling.mdx
website/content/docs/plugins/benchmark.mdx
website/content/docs/plugins/pg-vector-selector.mdx
website/content/docs/setup.mdx
website/content/docs/websocket/client.mdx
website/content/docs/websocket/index.mdx
website/content/docs/websocket/nestjs.mdx
website/content/docs/websocket/nodejs.mdx
website/content/index.mdx

This pull request includes changes to multiple documentation files, primarily adding the `copy` option to code blocks for easier copying of code samples. The most important changes are grouped by the affected files.
Changes to `website/content/docs/plugins/benchmark.mdx`:
* Added `copy` option to all `typescript` code blocks for easier copying. [[1]](diffhunk://#diff-1c92e38dd15b636af53e6a1e885e499fe1abb8aabf6914c0a1f84b9b7d6711e3L40-R40) [[2]](diffhunk://#diff-1c92e38dd15b636af53e6a1e885e499fe1abb8aabf6914c0a1f84b9b7d6711e3L63-R63) [[3]](diffhunk://#diff-1c92e38dd15b636af53e6a1e885e499fe1abb8aabf6914c0a1f84b9b7d6711e3L206-R206) [[4]](diffhunk://#diff-1c92e38dd15b636af53e6a1e885e499fe1abb8aabf6914c0a1f84b9b7d6711e3L330-R330) [[5]](diffhunk://#diff-1c92e38dd15b636af53e6a1e885e499fe1abb8aabf …

docs: add copy component for code 

---

packages/core/src/chatgpt/ChatGptDescribeFunctionAgent.ts
packages/core/src/events/AgenticaDescribeEvent.ts
packages/core/src/events/AgenticaTextEvent.ts
packages/core/src/internal/MPSCUtil.ts
test/src/features/test_base_streaming_describe.ts
test/src/features/unit/async_queue/test_async_queue_base.ts
test/src/features/unit/mpsc/test_mpsc_base.ts
test/src/features/unit/mpsc/test_mpsc_wait_close.ts

Previously, done and waitClose only checked whether the writer was closed.
As a result, waitClose could be triggered even when the reader was not closed.
I have made modifications accordingly, but I have one question:
Would it be better to separate the closing state of the reader and the writer in this case?

fix: rename waitClose to waitDone and make the criteria for 'done' more re rigorous

---

packages/cli/package.json
packages/cli/src/utils/getNpmPackages.ts

Removed axios dependency from packages/cli by replacing the API call with native fetch in getNpmPackages.ts, reducing bundle size and dependencies.
This pull request includes changes to the `packages/cli` to remove the `axios` dependency and replace it with the native `fetch` API for making HTTP requests. The changes also include minor formatting adjustments.
Dependency removal and replacement:
* [`packages/cli/package.json`](diffhunk://#diff-6e2e2a1851648938b325ba84de634407a4e69a644ea61102df15ca4a8a7a9758L45): Removed the `axios` dependency.
* [`packages/cli/src/utils/getNpmPackages.ts`](diffhunk://#diff-57441632a2a5129de1e51727b2b1e77711dd035485a67d06ef36ce1f7964962bL1): Removed the import statement for `axios` and replaced the `axios.get` call with the `fetch` API. …

fix(cli): replace axios with native fetch

---

packages/cli/package.json
packages/cli/src/executable/AgenticaStart.ts
packages/cli/src/utils/getNpmPackages.ts

This pull request includes several changes to the `packages/cli` that improve the handling of project templates and update dependencies. The most important changes include replacing the `clone` function with `writeTemplate`, removing `axios` in favor of `fetch`, and updating the dependencies in `package.json`.
* [`packages/cli/src/executable/AgenticaStart.ts`](diffhunk://#diff-a96f3ceac5d81d41e64a77cf1f4e42889aba41e66ac7f6d3475782be7f379b7aR4): Replaced the `clone` function with `writeTemplate` to use `giget` for downloading project templates. This change includes importing `downloadTemplate` from `giget` and modifying the function to use `downloadTemplate` instead of `git clone`. [[1]](diffhunk://#diff-a96f3ceac5d81d41e64a77cf1f4e42889aba41e66ac7f6d3475782be7f379b7aR4) …

fix: remove git command execution

---

packages/cli/package.json

This pull request includes a small change to the `packages/cli/package.json` file. The change involves moving the `typia` package from `devDependencies` to `dependencies`. 
* [`packages/cli/package.json`](diffhunk://#diff-6e2e2a1851648938b325ba84de634407a4e69a644ea61102df15ca4a8a7a9758L50-R59): Moved `typia` package from `devDependencies` to `dependencies` section.

fix(cli): typia should be the `dependencies`

---

packages/cli/src/executable/AgenticaStart.ts

Use dynamic import for prettier and handle the case when it's not available in dependencies by falling back to the original content. Otherwise, the import will fail and the CLI will not work.
This pull request includes changes to the `packages/cli/src/executable/AgenticaStart.ts` file to address dependency management and improve the formatting process. The key changes involve removing a direct import of `prettier` and handling it dynamically within the function.
Dependency management and formatting process:
* Removed the direct import of `prettier` to avoid issues with missing dependencies. (`[packages/cli/src/executable/AgenticaStart.tsL6](diffhunk://#diff-a96f3ceac5d81d41e64a77cf1f4e42889aba41e66ac7f6d3475782be7f379b7aL6)`)
* Updated the formatting function to dynamically import …

fix(cli): make prettier dynamic import

---

website/content/docs/core/config.mdx

This pull request includes updates to the documentation to provide more detailed guidance on configuring system prompts for internal agents. The changes focus on explaining how to use the `IAgenticaSystemPrompt` properties and the impact of the `common` property configuration.
Documentation updates:
* [`website/content/docs/core/config.mdx`](diffhunk://#diff-0c3fc75dd202f085970b239482af7d2cd71137c3f921edb19eeb0e075fc8bbccR162-R171): Added a detailed explanation of system prompts for internal agents, including how to configure `IAgenticaSystemPrompt` properties and the `common` property to guide agents' behavior.

Guidance of system prompt configuration

---

packages/cli/src/executable/AgenticaStart.ts

Replace third-party rimraf dependency with Node's native fs.rm for removing .git directory and .github/dependabot.yml. if use run `npx rimraf`, even user use pnpm, npm is used.
===
This pull request includes changes to the `AgenticaStart` namespace in the `packages/cli/src/executable/AgenticaStart.ts` file. The primary focus of these changes is to improve the method of removing directories by using asynchronous file system operations instead of synchronous ones.
Key changes include:
* [`packages/cli/src/executable/AgenticaStart.ts`](diffhunk://#diff-a96f3ceac5d81d41e64a77cf1f4e42889aba41e66ac7f6d3475782be7f379b7aL176-R179): Replaced synchronous `cp.execSync` calls with asynchronous `fs.rm` calls to remove the `.git` directory and the `.github/dependabot.yml` file.

fix(cli): replace rimraf with native fs.rm

---

packages/cli/src/bases/Package.ts

Add TypeScript exhaustive type checking for package managers to ensure all cases are properly handled. The change improves type safety by making future additions to package manager types fail compilation if not explicitly handled in the switch statement.
This pull request includes a change to the `Package` namespace in the `packages/cli/src/bases/Package.ts` file to improve error handling for unsupported package managers.
Error handling improvement:
* [`packages/cli/src/bases/Package.ts`](diffhunk://#diff-f44345d2056ed241a54344cbfffe342936713a3f226be146eee4543474f8e6ffR41-R45): Added a default case to the `switch` statement to handle unsupported package managers by throwing an error, ensuring exhaustive checks.

feat(cli): add exhaustive type check for package managers

---

website/app/_components/common/dropdown-menu.tsx

This pull request focuses on making the code style consistent across the `website/app/_components/common/dropdown-menu.tsx` file by ensuring all import statements and function definitions end with semicolons. Additionally, it comments out some icon components within the dropdown menu items.
Code style improvements:
* Added semicolons at the end of all import statements and function definitions to ensure consistency and adherence to coding standards. [[1]](diffhunk://#diff-79dee3ae094221d893564a2a6e0b17fa08187e1c4ad8291e66616f6417a0bbc2L1-R19) [[2]](diffhunk://#diff-79dee3ae094221d893564a2a6e0b17fa08187e1c4ad8291e66616f6417a0bbc2L31-R30) [[3]](diffhunk://#diff-79dee3ae094221d893564a2a6e0b17fa08187e1c4ad8291e66616f6417a0bbc2L46-R58) …

Detour icon bugs of landing page for a while

---

packages/cli/src/bases/Package.ts
packages/cli/src/bases/Tsconfig.ts
packages/cli/src/functional/AgenticaStarter.ts

The standalone project is single execution file, never be a library  
so i rename the `agent.ts` to `index.ts` and `lib` to `dist`  
---
This pull request includes several changes to improve the file structure and error handling in the `packages/cli` module. The most important changes include updating script paths, modifying the output directory, and refining error messages.
* [`packages/cli/src/bases/Package.ts`](diffhunk://#diff-f44345d2056ed241a54344cbfffe342936713a3f226be146eee4543474f8e6ffL18-R19): Updated the `dev` and `start` script paths to use `src/index.ts` and `dist/index.js` respectively.
* [`packages/cli/src/bases/Tsconfig.ts`](diffhunk://#diff-e83d9ad6448a97275f7ef71dfb1126da526faded23cc06e62977feb75af3962dL69-R69): Changed the `outDir` configuration from `./lib` to `./dist` …

fix(cli): wrong project configure on standalone project type

---

packages/cli/package.json
pnpm-lock.yaml

This pull request includes changes to the `packages/cli/package.json` and `pnpm-lock.yaml` files to remove unused dependencies.
Dependency removal:
* [`packages/cli/package.json`](diffhunk://#diff-6e2e2a1851648938b325ba84de634407a4e69a644ea61102df15ca4a8a7a9758L43-L46): Removed `comment-json` and `package-manager-detector` dependencies. and move `typia` from deps to devDeps
* [`pnpm-lock.yaml`](diffhunk://#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL208-L219): Removed `comment-json` and `package-manager-detector` dependencies from the importers section.

fix(cli): removed unused deps

---

packages/cli/package.json
packages/create-agentica/index.js
packages/create-agentica/package.json
pnpm-lock.yaml

I found that we don't have`create-agentica` package in npm.
`create-???` package has an important mean!
https://www.alexchantastic.com/building-an-npm-create-package
If we have `create-agentica` package, the user can start agentica project like:
```
npm create agentica@latest
pnpm create agentica
yarn create agentica
bun create agentica
```
There is already an `agentica` cli in this project, so the segregation should be considered. For now, `create-agentica` is just an alias for `agentica` cli. We need to modify the content, and discuss the contents later.
In any case, it seems important that we secure this name ourselves before someone else takes this package.
I'm going to bed now and won't be able to work on it for a few hours, so if there's anything that needs fixing, please fix it and …

feat: introducing `create-agentica`

---

.github/workflows/build.yml
.github/workflows/release.yml
.github/workflows/website.yml
.npmrc
package.json

This pull request includes several changes to update the Node.js and `pnpm` versions used in the project. The most important changes include modifications to the GitHub Actions workflows, updates to the `package.json` file, and the addition of a new `.npmrc` configuration.
Updates to GitHub Actions workflows:
* [`.github/workflows/build.yml`](diffhunk://#diff-5c3fa597431eda03ac3339ae6bf7f05e1a50d6fc7333679ec38e21b337cb6721L13-L18): Removed the `node-version` and `pnpm` version specifications.
* [`.github/workflows/release.yml`](diffhunk://#diff-87db21a973eed4fef5f32b267aa60fcee5cbdf03c67fafdc2a9b553bb0b15f34L16-L20): Removed the `node-version` and `pnpm` version specifications.
* [`.github/workflows/website.yml`](diffhunk://#diff-c7731b29de71fca225e1dfac88ebe31975a4cd9759ab13e91d86eeadafbd …

manage pnpm & node version by pnpm

---

packages/core/src/chatgpt/ChatGptCompletionMessageUtil.ts

ChatCompletionChunk.usage type is `CompletionUsage | undefined`, but actually value is `CompletionUsage | null`,
but typia builds before to build library.

fix(core): add additional null type for unspecified value from openai

---

packages/create-agentica/package.json

```
Done in 3.7s using pnpm v10.6.4
 ERR_PNPM_NO_SCRIPT  Missing script: build
But script matched with build is present in the root of the workspace,
so you may run "pnpm -w run build"
node:child_process:966
throw err;
^
Error: Command failed: pnpm run build
at genericNodeError (node:internal/errors:984:15)
at wrappedFn (node:internal/errors:538:14)
at checkExecSyncError (node:child_process:891:11)
at Object.execSync (node:child_process:963:15)
at execute (/home/runner/work/agentica/agentica/deploy/publish.js:14:8)
at build (/home/runner/work/agentica/agentica/deploy/publish.js:19:3)
at /home/runner/work/agentica/agentica/deploy/publish.js:82:5
at Array.forEach (<anonymous>)
at main (/home/runner/work/agentica/agentica/deploy/publish.js:81:18)
at Object.<anonymous> …
```

revert(create-agentica): revert empty build scripts

---

.github/workflows/release.yml

Change release workflow to trigger on tag push instead of release creation. Add automatic GitHub release creation with changelogithub after successful npm publish.
So the release flow changes.
When you want to release new package,
```sh
cd (git root)
pnpm i
pnpm release
```
Then, then versions in package.json are updated and git tags are created automatically
When tag is pushed, GH Actions publish packages to npm, and create release automatically!

feat(ci): improve release workflow automation

---

.github/workflows/lint-check.yml
.github/workflows/spell-check.yml

because this repository is public, we can use github actions without limits.
Also sometimes people push commits on main, which doesn't makes CI run.
This PR makes CI run on every push/pr

feat: check lint on push

---

.github/workflows/build-and-publish-dry-run.yml
.github/workflows/test.yml

we split build-pulblish-dry-run and test in different filees.
We use chatgpt api so e2e should be only on pull_request.
However, we can run build and upload it to pkg.pr.new everytime without worrying about any cost!

fix(ci): split test and publish-build-dry-run

---

.vscode/extensions.json

introduce typos vscode extenions 
this exteions is https://github.com/crate-ci/typos/ wrapper
---
As I understand it, it also plays the role of prettier in the eslint setup.
Is prettier deprecated now?
---
This pull request includes a small change to the `.vscode/extensions.json` file. The change adds a new recommended extension for VS Code, `tekumara.typos-vscode`, to the existing list of recommendations.

chore(*): introduce typos vscode extenstions

---

eslint.config.mts
package.json
packages/benchmark/package.json
packages/chat/package.json
packages/core/package.json
packages/pg-vector-selector/package.json
packages/rpc/package.json
pnpm-lock.yaml
test/package.json

- configure eslint on root
- ignores submodules
- `lint:fix` -> `format`
- run all lint commands using regex

feat: configure eslint on root

---

README.md
website/app/layout.jsx
website/content/docs/concepts/_meta.ts
website/next.config.ts

This pull request includes several changes to the `website` and `README.md` files to update documentation links, modify layout configurations, and adjust theme settings.
Documentation updates:
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L58-R59): Corrected the order of the "Document Driven Development" link in the concepts section.
* [`website/content/docs/concepts/_meta.ts`](diffhunk://#diff-d363de1c397f359217ce2e3450971dd9b62d590266024c06ac235352f315a54aL5-R6): Ensured consistent naming for "Document Driven Development" in the meta records.
Layout and theme adjustments:
* [`website/app/layout.jsx`](diffhunk://#diff-b43b1bc0a42db021ecb816f80baa2348806164da1b99c2584eed456d5f7c2e99L37-R40): Commented out the background color settings to …

Dark mode only

---

packages/rpc/package.json
pnpm-lock.yaml

This pull request primarily involves the removal of several dependencies from the `pnpm-lock.yaml` and `package.json` files. The key changes include removing dependencies such as `chalk`, `openai`, and `tstl`, along with related adjustments in the lock file.
Dependency removals:
* [`packages/rpc/package.json`](diffhunk://#diff-68aaf91f74a0ea0d392cd7e8a0bd6de0a8cff7abdd251b6b9875111556003650L51-L53): Removed `chalk`, `openai`, and `tstl` dependencies.
* [`pnpm-lock.yaml`](diffhunk://#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL356-L364): Removed `chalk`, `openai`, and `tstl` dependencies from the importers section.
Lock file adjustments:
* [`pnpm-lock.yaml`](diffhunk://#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL7080-R7071): Removed …

chore(rpc): remove unused package from deps

---

website/content/tutorial/productivity/google-scholar.mdx

This pull request adds a new tutorial for setting up a Google Scholar Agent using the Agentica CLI. The tutorial includes steps for setup, an overview of the generated code, and a use case example.
Key additions:
* Added a detailed setup guide for creating a Google Scholar Agent using the Agentica CLI.
* Included a code snippet demonstrating the generated code for the Google Scholar Agent, which uses OpenAI's GPT model and the `GoogleScholarService` connector.
* Provided instructions for setting up environment variables in a `.env` file to securely manage API keys.
* Added a use case example to illustrate how the agent can be used to perform intelligent searches on Google Scholar.
* Linked to the source code for the `GoogleScholarService` to offer a complete list of available functions.

docs(website): add google scholar tutorial

---

website/content/tutorial/productivity/reddit.mdx

This pull request introduces a new tutorial for setting up a Reddit Agent using the Agentica CLI. The tutorial provides a comprehensive guide, from the initial setup to the functionalities of the generated code.
Key changes include:
* Added a new tutorial file `website/content/tutorial/productivity/reddit.mdx` for setting up a Reddit Agent with Agentica CLI. This includes sections on introduction, quick CLI setup, generated code overview, functionalities, and use case examples.
* Detailed instructions on launching the Agentica Setup Wizard and configuring the Reddit Agent, including necessary environment variables and credentials.
* Explanation of the generated code and its components, such as the `RedditService` and integration with OpenAI's GPT model.
* List of available functions …

docs(website): add reddit tutorial

---

website/content/tutorial/productivity/google-scholar.mdx

This pull request includes a small change to the `website/content/tutorial/productivity/google-scholar.mdx` file. The change adds a title to the Google Scholar Agents tutorial.
* [`website/content/tutorial/productivity/google-scholar.mdx`](diffhunk://#diff-def6ec037c5acde0f5bb6038b0fd7cb72a5751c2557cc7843bba032ed0a7d0d4R1-R4): Added a title to the Google Scholar Agents tutorial.

docs(website): fix google scholar tutorial 

---

packages/cli/build.config.ts

Change the import path for UnpluginTypia to use the rollup version instead of the vite version in the CLI build configuration.

fix(cli): UnpluginTypia sholud be a rollup plugin

---

packages/benchmark/package.json
packages/chat/package.json
packages/cli/package.json
packages/core/package.json
packages/rpc/package.json
pnpm-lock.yaml
test/package.json

This pull request includes several updates to dependencies across multiple packages. The primary focus is on upgrading versions of `@samchon/openapi`, `typia`, and related dependencies to ensure compatibility and leverage new features.
* Updated `@samchon/openapi` from `^3.0.0` to `^3.2.0` in multiple `package.json` files. [[1]](diffhunk://#diff-03d34ead8faa24fcf5b6d74b52eaf57db4400f375b60698e3f5024e28b29b0e1L50-R53) [[2]](diffhunk://#diff-0b810c38f3c138a3d5e44854edefd5eb966617ca84e62f06511f60acc40546c7L52-R57) [[3]](diffhunk://#diff-68aaf91f74a0ea0d392cd7e8a0bd6de0a8cff7abdd251b6b9875111556003650L50-R51)
* Updated `typia` from `^8.0.0` to `^8.0.4` in multiple `package.json` files. [[1]](diffhunk://#diff-162e61feb520f86e5b6de240f53beb7e78cc2846c0659c041848042f089a658cL51-R58) …

Bump up dependencies to avoid samchon/typia#1554

---

packages/cli/src/commands/start.ts

currently, when select the connectors on Agentca cli in NestJS Template, The original controller `BbsArticle` is not removed.
so, we need to remove that code.
also It has an error that user doesn't select any connector, BbsArticle is kept in template, but removed.
- Add to remove the `BbsArticle`
- Add the logic when user doesn't any connector, keep the BbsArticle in template.

fix(cli): remove BbsArticle when select connectors in NestJS Template

---

website/content/tutorial/productivity/notion.mdx

This pull request includes a small change to the `website/content/tutorial/productivity/notion.mdx` file. The change updates the YouTube video embed URL format.
* [`website/content/tutorial/productivity/notion.mdx`](diffhunk://#diff-ba819cbcbecfb72ec7460fd8fac1c87eb0d84d36af2110eabe64d7cdae400a9eL9-R9): Changed the `src` attribute of the `iframe` element from `https://www.youtube.com/shorts/hzkNNt7bvUQ` to `https://www.youtube.com/embed/hzkNNt7bvUQ`.

fix(website): wrong youtube short url

---

packages/cli/.gitignore
packages/cli/bin/index.mjs
packages/cli/build.config.ts
packages/cli/src/index.test.ts
packages/cli/src/index.ts
packages/cli/tsconfig.json
packages/create-agentica/index.js

you can check it with `pnpm run node ./bin/index.mjs --version`
Implement version support in the CLI tool by:
- Importing package.json version in build config
- Adding environment variable replacement during build
- Setting up version command in the CLI program
This allows users to check the CLI version with --version flag.
This pull request includes changes to the `packages/cli` to integrate the version from `package.json` into the build process and CLI version display. The most important changes include importing the `package.json` file, adding a replace configuration for the version, and defining the version constant in the CLI source code.
* [`packages/cli/build.config.ts`](diffhunk://#diff-9a7382d3037f737c8c0654204114d28ce916c4944d7dd8608f19cf27f63b73e0R3): Imported `package.json` to …

feat(cli): add version support to command line interface

---

packages/benchmark/package.json
packages/chat/package.json
packages/cli/package.json
packages/core/package.json
packages/pg-vector-selector/package.json
packages/rpc/package.json
pnpm-lock.yaml
test/package.json

Updated with:
```sh
pnpx taze -wr --include typia,@samchon/openapi
pnpm install
```
This pull request includes various updates to package dependencies across multiple files, primarily upgrading the versions of `@samchon/openapi` and `typia` packages.
Dependency Updates:
* Updated `@samchon/openapi` from `^3.2.0` or `^3.0.0` to `^3.2.2` in `package.json` files for `benchmark`, `chat`, `core`, `pg-vector-selector`, and `rpc` packages. [[1]](diffhunk://#diff-03d34ead8faa24fcf5b6d74b52eaf57db4400f375b60698e3f5024e28b29b0e1L50-R53) [[2]](diffhunk://#diff-162e61feb520f86e5b6de240f53beb7e78cc2846c0659c041848042f089a658cL44-R51) [[3]](diffhunk://#diff-0b810c38f3c138a3d5e44854edefd5eb966617ca84e62f06511f60acc40546c7L56-R57) [[4]](diffhunk://#diff-17c97c54e8f9e9e170b125f77d0288d568fcbc648384108b8834 …

chore(deps): update `@samchon/openapi` and `typia`

---

package.json
pnpm-lock.yaml

This pull request includes updates to several dependencies in the `package.json` and `pnpm-lock.yaml` files. The most important changes involve the addition of new dependencies and updates to existing ones.
Dependency updates and additions:
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R61): Added `eslint-plugin-format` version `^1.0.1`.
* [`pnpm-lock.yaml`](diffhunk://#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL19-R28): Added `eslint-plugin-format` version `1.0.1` under `importers` and `snapshots`. [[1]](diffhunk://#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL19-R28) [[2]](diffhunk://#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbR7420-R7470)
* …

chore(*): add **eslint-plugin-format** for to fix style lint error

---

packages/cli/package.json

This pull request includes a small change to the `packages/cli/package.json` file. The change adds the `dist` directory to the list of files included in the package.

fix(cli): publishing config

---

packages/cli/build.config.ts

This pull request includes a small change to the `packages/cli/build.config.ts` file. The change enables the generation of source maps in the build configuration.
* [`packages/cli/build.config.ts`](diffhunk://#diff-9a7382d3037f737c8c0654204114d28ce916c4944d7dd8608f19cf27f63b73e0R25): Added the `sourcemap` option to the build configuration to generate source maps.

feat(cli): add map file for trace error

---

website/content/tutorial/coding/swagger.mdx

The petStore swagger is an incorrectly written specification and does not work smoothly, so correct it.

docs(website): replace petStore example to shopping-backend

---

packages/cli/src/commands/start.ts

- fix the order of packageMangaer install command in `installServicesAsDependencies`

fix: fix the order of packagemanger install

---

packages/core/build/prompt.js

This pull request includes a small change to the `async function main()` in the `packages/core/build/prompt.js` file. The change updates the file path for writing the `AgenticaSystemPrompt.ts` file.
* [`packages/core/build/prompt.js`](diffhunk://#diff-977c3a67c50403a73980530b0478352c2698fa59682eee22bd20f86c8a35a4e6L24-R24): Updated the file path from `../src/internal/AgenticaSystemPrompt.ts` to `../src/constants/AgenticaSystemPrompt.ts` in the `fs.promises.writeFile` call.

fix(core): prepare command error

---

.github/workflows/test.yml
packages/cli/.gitignore
packages/cli/src/commands/start.test.ts
packages/cli/src/commands/start.ts
packages/cli/src/packages.test.ts
packages/cli/src/packages.ts

This pull request includes several changes to the testing setup, package management, and codebase simplification. The most important changes include adding support for multiple Node.js versions in the CI workflow, refactoring the test setup to use temporary directories, and updating package manager commands.
* [`.github/workflows/test.yml`](diffhunk://#diff-faff1af3d8ff408964a57b2e475f69a6b7c7b71c9978cccc8f471798caac2c88R11-R20): Added a strategy matrix to test against multiple Node.js versions (18.x, 20.x, 22.x) and configured the setup to use the appropriate Node.js version for each job.
* [`packages/cli/src/commands/start.test.ts`](diffhunk://#diff-cad17d10af917b03d1bcd2cbe447e2e6caed5226042bde8c47133f2017c9cbcbL3-R46): Refactored the test setup to use temporary directories generated …

test(cli): stop mocking for start command and test with all package managers

---

packages/cli/src/packages.test.ts
packages/cli/src/packages.ts

Added null coalescence to handle undefined package parameter in npm, pnpm, and bun install commands, ensuring they still generate valid commands even when no package is specified. Added tests to verify this behavior.

fix(cli): handle undefined package in install commands

---

packages/cli/package.json

we test our cli with node.js 18 and it works!
So we modify `engine` field

fix(cli): lower Node.js version requirement to 18.18.0

---

.github/workflows/lint-check.yml

This pull request includes a change to the linting job in the GitHub Actions workflow file `.github/workflows/lint-check.yml`. The change updates the command used for linting to simplify the process and ensure proper error handling.
Changes to linting job:
* [`.github/workflows/lint-check.yml`](diffhunk://#diff-dda267615bb53af994fa659ec8de11a5c4855ee18b1922370924f65759d8cae1L19-R19): Updated the linting command to use `pnpm dlx npm-run-all2 -p lint:* --aggregate-output` instead of the previous command which manually checked the output for errors.

fix(ci): breaked lint-check on CI

---

packages/cli/package.json
packages/pg-vector-selector/eslint.config.mts
packages/pg-vector-selector/package.json
packages/pg-vector-selector/src/AgenticaPgVectorSelector.ts
packages/pg-vector-selector/src/utils.test.ts
packages/pg-vector-selector/src/utils.ts
packages/pg-vector-selector/tsconfig.build.json
packages/pg-vector-selector/tsconfig.json
packages/pg-vector-selector/vitest.config.mts
pnpm-lock.yaml
pnpm-workspace.yaml
test/src/features/test_benchmark_call_pg_vector_selector.ts

This pull request includes several updates across multiple files to integrate the `vitest` testing framework and improve the code structure by moving utility functions to a separate file. The most important changes include updating dependencies, modifying configurations, and adding new utility functions with corresponding tests.
* [`packages/cli/package.json`](diffhunk://#diff-6e2e2a1851648938b325ba84de634407a4e69a644ea61102df15ca4a8a7a9758L72-R72): Updated the `vitest` dependency to use `catalog:vite`.
* [`packages/pg-vector-selector/package.json`](diffhunk://#diff-17c97c54e8f9e9e170b125f77d0288d568fcbc648384108b88347b62b6f5e09fL44-R45): Added `vitest` as a dependency and a new `test` script to run `vitest`. [[1]](diffhunk://#diff-17c97c54e8f9e9e170b125f77d0288d568fcbc648384108b88347b62b6 …

feat(pg-vector-selector): add unit test

---

packages/cli/src/packages.test.ts

Add the test code about `runCommand` in `packages.ts` of Agentica CLI.
- `packages/cli/src/packages.test.ts` : Add unit test about `runCommand`
- fixes: #304

test(cli): add runCommand Unit Test in Agentica CLI

---

.github/dependabot.yml
packages/benchmark/package.json
packages/chat/package.json
packages/cli/package.json
packages/core/package.json
packages/pg-vector-selector/package.json
packages/rpc/package.json
pnpm-lock.yaml
pnpm-workspace.yaml
test/package.json
test/src/features/test_base_work_describe.ts

https://github.blog/changelog/2025-02-04-dependabot-now-supports-pnpm-workspace-catalogs-ga/
Github says dependabot is supporting pnpm catalog.
Let's test it.
---------------
This pull request includes updates to the dependency management and versioning strategy across multiple packages. The changes primarily focus on updating the dependencies and ensuring consistency in the package catalog references.
Dependency management updates:
* [`.github/dependabot.yml`](diffhunk://#diff-dd4fbda47e51f1e35defb9275a9cd9c212ecde0b870cba89ddaaae65c5f3cd28R1-R29): Added a new configuration for dependabot to manage npm dependencies using pnpm, with specific groups for `typia`, `typescript`, and `vendor` dependencies.
Catalog reference updates:
* …

Prepare dependabot.

---

packages/rpc/src/AgenticaRpcService.ts
packages/rpc/src/IAgenticaRpcListener.ts
test/src/features/rpc/test_rpc_websocket_call.ts
test/src/features/rpc/test_rpc_websocket_initialize.ts

This pull request includes several changes to the RPC service and its associated tests. The most important changes involve updating the type definitions, adding a new test for WebSocket calls, and renaming and modifying an existing test.
* Updated the return type of the `call` method in the `IAgenticaRpcListener` interface to include `void` as a possible return type. (`packages/rpc/src/IAgenticaRpcListener.ts`, [packages/rpc/src/IAgenticaRpcListener.tsL108-R108](diffhunk://#diff-a7449615bfcbf476b208fba4f3ce6cf07efc4e9021702d06c8c920a71c6ea599L108-R108))
* Modified the `call` method in the `AgenticaRpcService` to handle the updated return type of the `call` method in the `IAgenticaRpcListener` interface. (`packages/rpc/src/AgenticaRpcService.ts`, …

test(rpc): check websocket's serialization

---

packages/core/src/utils/ChatGptCompletionMessageUtil.ts

As type assertion on `ChatCompletionChunk` fails too much a lot (no one is keeping the type exactly), determine not to type assertion strictly.

No assert chat completion chunk

---

website/app/layout.jsx

The footer previously used only on the landing page has been updated to be a shared footer used across all sections.
before:
after:

fix(web): normalize footer

---

website/app/_components/layout/Footer.tsx

This pull request includes a small change to the `website/app/_components/layout/Footer.tsx` file. The change adds a link to the Discord server in the footer.
* [`website/app/_components/layout/Footer.tsx`](diffhunk://#diff-fbe7438c69ee8a131445c3bfa6db33e554ff31312166e75957881a720bca4427R26): Added a new footer link to the Discord server.

feat(web): add additional link about developer section on footer

---

package.json
packages/core/src/orchestrate/call.ts
packages/core/src/orchestrate/cancel.ts
packages/core/src/orchestrate/execute.ts
packages/core/src/orchestrate/internal/cancelFunction.ts
test/src/features/test_micro_agentica.ts

This pull request includes several changes to the `packages/core/src/orchestrate` module and related files to simplify the codebase and improve functionality. The most important changes involve removing unnecessary asynchronous calls, updating function signatures, and adding error logging.
* [`packages/core/src/orchestrate/call.ts`](diffhunk://#diff-fab757df7c77323a0efe9872a53054b76585edada69dc8515773aa7b598a023eL30-R30): Removed the `createCancelEvent` import and updated the return type of closures to use an array instead of a tuple. [[1]](diffhunk://#diff-fab757df7c77323a0efe9872a53054b76585edada69dc8515773aa7b598a023eL30-R30) [[2]](diffhunk://#diff-fab757df7c77323a0efe9872a53054b76585edada69dc8515773aa7b598a023eL119-R119)
* [`packages/core/src/orchestrate/call.ts`](diffhunk://#diff-fab7 …

fix(core): not to emit select history from `MicroAgentica`.

---

packages/core/src/Agentica.ts
packages/core/src/MicroAgentica.ts
packages/core/src/orchestrate/call.ts
packages/core/src/orchestrate/cancel.ts
packages/core/src/orchestrate/initialize.ts
packages/core/src/orchestrate/select.ts
test/src/TestGlobal.ts
test/src/features/bugs/test_bug_openrouter_streaming.ts

In the OpenAI SDK, if no text message comes from the AI agent, it must become `null` value.
However, `openrouter` ignores the rule, and just assign the zero length string value.
This PR avoids such domain bug of openrouter by checking string length.
-----------------
This pull request introduces a new feature for OpenRouter streaming and updates the environment configuration to support it. The key changes include adding a new API key to the environment interface and implementing a test function for OpenRouter streaming.
* [`test/src/TestGlobal.ts`](diffhunk://#diff-35da97a7f8d40740805b0a37c632c25ba24082e30adfead3ef6045e06f7eb086R52): Added `OPENROUTER_API_KEY` to the `IEnvironments` interface to support the new OpenRouter streaming feature.
* …

Fix(core): bug of streaming (openrouter only)

---

packages/core/src/Agentica.ts
packages/core/src/MicroAgentica.ts
packages/core/src/events/AgenticaDescribeEvent.ts
packages/core/src/events/AgenticaResponseEvent.ts
packages/core/src/events/AgenticaTextEvent.ts
packages/core/src/factory/events.ts
packages/core/src/orchestrate/call.ts
packages/core/src/orchestrate/describe.ts
packages/core/src/orchestrate/initialize.ts
packages/core/src/orchestrate/select.ts
packages/core/src/transformers/AgenticaEventTransformer.ts
packages/core/src/utils/StreamUtil.ts
test/src/features/test_base_streaming.ts
test/src/features/test_base_streaming_describe.ts
test/src/features/unit/stream/test_stream_from.ts

This pull request includes several changes to the `Agentica` and `MicroAgentica` classes, focusing on updating the stream handling mechanism from `ReadableStream` to `AsyncGenerator` across various files. The most important changes are grouped by theme and listed below:
* Updated imports and usage of stream utilities to use `toAsyncGenerator` and `streamDefaultReaderToAsyncGenerator` in `Agentica` and `MicroAgentica` classes (`packages/core/src/Agentica.ts`, `packages/core/src/MicroAgentica.ts`). [[1]](diffhunk://#diff-fd17ccaf3913505148ef799667fe621b8664f52622f44959be527d79c5109898L25-R25) [[2]](diffhunk://#diff-fd17ccaf3913505148ef799667fe621b8664f52622f44959be527d79c5109898L137-R137) [[3]](diffhunk://#diff-fd17ccaf3913505148ef799667fe621b8664f52622f44959be527d79c5109898L285-R285) …

feat(core): Change the difficult stream to a more familiar generator.

---

packages/core/src/functional/assertMcpLlmApplication.ts

MCP SDK does not work on browser.
I think `assertMcpLlmApplication()` function, it would better to get schema values directly.

fix(core): emergent bug patch for browser.

---

website/content/docs/core/controller/swagger.mdx
website/content/docs/core/controller/typescript.mdx
website/content/docs/index.mdx
website/content/docs/plugins/openai-vector-store.mdx

This pull request includes several changes to the documentation files to embed YouTube videos and update the description of `@agentica`. The most important changes include the addition of iframes for YouTube videos and updates to the description of `@agentica`.
* [`website/content/docs/core/controller/swagger.mdx`](diffhunk://#diff-4d2606759cd72db8c3b0b8ff639c666cd86e68de35cc425656377a75de11ec63R10-R19): Added an iframe to embed a YouTube video titled "Plug in OpenAPI, Get an AI Agent".
* [`website/content/docs/core/controller/typescript.mdx`](diffhunk://#diff-4ba45f22ef80d3b4b8cf4454a87428e7af7546a93e1717a2118828db77382433R15-R24): Added an iframe to embed a YouTube video titled "Turn Your TypeScript Class into an AI Agent".
* [`website/content/docs/plugins/openai-vector-store.mdx`](diffh …

docs(website): some videos

---

benchmark/pg-vector-selector-benchmark/src/runShoppingBenchmark.ts

This pull request updates the `runShoppingBenchmark` function in `benchmark/pg-vector-selector-benchmark/src/runShoppingBenchmark.ts` to use a different benchmark class and modifies its configuration. The changes focus on aligning the function with the `AgenticaSelectBenchmark` class and increasing the benchmark's repeat count.
* Replaced `AgenticaCallBenchmark` with `AgenticaSelectBenchmark` for both the imported class and the return type of the `runShoppingBenchmark` function to reflect the new benchmark type.
* Updated the instantiation of the benchmark object to use `AgenticaSelectBenchmark` and increased the `repeat` configuration value from `10` to `100` for more extensive testing.

fix(pg-vector-selector): benchmark type

---

packages/benchmark/src/AgenticaSelectBenchmark.ts
packages/core/src/structures/IAgenticaConfig.ts

This pull request introduces changes to improve the flexibility and error handling of the `AgenticaSelectBenchmark` class by updating how the context is managed and enhancing type imports in the `IAgenticaConfig` structure. The key updates include replacing direct calls to the `select` function with dynamic executor selection and adding a new type import for better type management.
* Replaced direct calls to the `select` function with a dynamic executor selection mechanism. If the `executor` function is not found in the context configuration, an error is thrown to improve error handling.
* Added a new type import for `Agentica` in `IAgenticaConfig.ts` to improve type clarity and maintainability.

fix(benchmark): select benchmark should receive new select function

---

packages/cli/src/commands/start.ts
packages/cli/src/index.test.ts
packages/cli/src/index.ts

This pull request refactors the handling of starter templates in the CLI and enhances the `commander` program's option definition for better maintainability and type safety. The most important changes include introducing a constant array for starter templates, updating the `StarterTemplate` type to derive from this array, and improving the `commander` option definition to use `.choices()`.
* [`packages/cli/src/commands/start.ts`](diffhunk://#diff-6858dc88bcb8c8d88063b185a5bddbe2709171731c56c401cbf793bf7ff5baa1R25-R36): Introduced a `START_TEMPLATES` constant array to list all supported starter templates and updated the `StarterTemplate` type to derive its values from this array using `typeof START_TEMPLATES[number]`. This improves maintainability by centralizing the template definitions. …

feat(cli): use choices for project option

---

packages/benchmark/src/internal/AgenticaSelectBenchmarkReporter.ts

This pull request enhances the reporting capabilities of the `AgenticaSelectBenchmarkReporter` by adding error metrics and fixing a property access issue for token usage. These changes improve the clarity and accuracy of benchmark reports.
* Added a new "Error" metric to the trial and experiment summaries to track the number of error events. (`writeIndex` and `writeExperimentIndex` in `packages/benchmark/src/internal/AgenticaSelectBenchmarkReporter.ts`) [[1]](diffhunk://#diff-8759e5db5d9c02ac643aaba52c04b9ddd16ed7d98a099c1bc6ac8da3cca228bdR58) [[2]](diffhunk://#diff-8759e5db5d9c02ac643aaba52c04b9ddd16ed7d98a099c1bc6ac8da3cca228bdR110)
* Corrected the property access for the "Total" token usage in event reporting by explicitly accessing the `total` property of `event.usage.aggregate`. …

fix(benchmark): add error count and fix total token usage on report format

---

packages/chat/package.json
pnpm-lock.yaml

This pull request removes unused ESLint plugins related to React from the project dependencies and updates the `pnpm-lock.yaml` file accordingly. These changes help streamline the codebase and reduce unnecessary dependencies.
* [`packages/chat/package.json`](diffhunk://#diff-162e61feb520f86e5b6de240f53beb7e78cc2846c0659c041848042f089a658cL75-L76): Removed `eslint-plugin-react-hooks` and `eslint-plugin-react-refresh` from the `devDependencies` section.
* [`pnpm-lock.yaml`](diffhunk://#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL233-L238): Removed `eslint-plugin-react-hooks` and `eslint-plugin-react-refresh` entries under `importers:` to reflect their removal from the project.
* [`pnpm-lock.yaml`](diffhunk://#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfd …

chore(chat): remove unused package

---

packages/cli/src/commands/start.ts

This pull request modifies the behavior of the `askQuestions` function in `packages/cli/src/commands/start.ts` to handle cases where the `envList` is empty more gracefully. The change ensures that the confirmation prompt is skipped entirely when there are no environment variables to enter.
Key change:
* Updated the `isConfirm` logic to automatically set the value to `false` if `envList` is empty, bypassing the confirmation prompt in such cases.

feat(cli): skip to set env step when env list length is 0(zero)

---

.github/ISSUE_TEMPLATE/bug-report.yaml

This pull request introduces a new bug report template for the repository to streamline the process of reporting issues and ensure that all necessary information is provided.
* [`.github/ISSUE_TEMPLATE/bug-report.yaml`](diffhunk://#diff-fe9734cc5d2a0e1916553dbc343214eab5630814c0b0a27d1370c4569afaea67R1-R50): Added a structured YAML template for bug reports, including fields for the Agentica version, platform details, bug description, reproduction steps, and validation checkboxes. This template ensures users provide a minimal reproducible example and verify there are no duplicate issues before submitting.

feat: add bug issue template

---

.github/workflows/test.yml

This pull request makes a minor change to the Node.js versions matrix in the GitHub Actions workflow configuration. The change removes support for Node.js version 18.x.
Node 18.x reaches its EOL on 30th April
* [`.github/workflows/test.yml`](diffhunk://#diff-faff1af3d8ff408964a57b2e475f69a6b7c7b71c9978cccc8f471798caac2c88L13-R13): Updated the `node-version` matrix to only include versions 20.x and 22.x, removing 18.x.

test(*): deprecate node 18

---

packages/core/src/MicroAgentica.ts

This pull request introduces a new functionality to the `MicroAgentica` class by adding support for retrieving operations encapsulated in the `AgenticaOperation` type. The changes also include importing the necessary `AgenticaOperation` module to support this functionality.
* **Importing `AgenticaOperation`:** Added an import statement for `AgenticaOperation` in `MicroAgentica.ts` to enable the use of this type in the class. (`[packages/core/src/MicroAgentica.tsR25](diffhunk://#diff-d0b41ca18164569e2f6b061dcac423715cca7eaa85200c4c1ed410f179850b28R25)`)
* **`getOperations` method:** Introduced a new public method `getOperations` to retrieve a list of operations encapsulated as `AgenticaOperation` objects. This method provides a readonly array of operations, enhancing the class's …

fix(core): add getOperation method on MicroAgentica

---

.github/workflows/release.yml
packages/benchmark/src/index.ts
packages/core/src/Agentica.ts
packages/core/src/context/AgenticaContext.ts

This pull request introduces support for abort signals in the `Agentica` class to enable cancellation of asynchronous operations. Additionally, it includes a minor reordering of exports in the `index.ts` file to maintain consistency.
* Added an `abortSignal` option to the `conversate` method, allowing users to pass an `AbortSignal` to cancel ongoing operations. Updated method signature and related JSDoc comments.
* Propagated the `abortSignal` through the `getContext` method and included it in the `AgenticaContext` interface. This ensures the signal is accessible throughout the execution context. [[1]](diffhunk://#diff-fd17ccaf3913505148ef799667fe621b8664f52622f44959be527d79c5109898R231) [[2]](diffhunk://#diff-8db8307cc84d1852618b218fd87e0f1ee31284644da9f0fea0adbe9f437756adR90-R94)
* …

feat(core): update interface for abortSignal

---

packages/core/src/utils/ChatGptCompletionMessageUtil.spec.ts
packages/core/src/utils/ChatGptTokenUsageAggregator.spec.ts
packages/core/src/utils/MathUtil.ts
packages/core/src/utils/Singleton.spec.ts
packages/core/src/utils/Singleton.ts
packages/core/src/utils/__map_take.spec.ts

This pull request introduces several new utility functions and their corresponding test cases, while also removing an unused utility. The most significant changes include adding comprehensive tests for `ChatGptCompletionMessageUtil`, `Singleton`, and `__map_take` utilities, and removing the `MathUtil` namespace. Below is a detailed breakdown of the changes:
* Added extensive test cases for `ChatGptCompletionMessageUtil`, covering methods like `transformCompletionChunk`, `accumulate`, `merge`, `mergeChoice`, and `mergeToolCalls`. These tests validate functionality such as JSON transformation, content accumulation, tool call merging, and usage aggregation.
* Introduced tests for the `Singleton` class to ensure proper instance creation, argument handling, and edge cases like null or …

test(core): add unit test code about util directory

---

packages/core/src/functional/assertMcpController.ts
packages/core/src/functional/validateMcpController.ts
packages/core/src/structures/IAgenticaController.ts

This pull request updates type-checking comments related to the `@modelcontextprotocol/sdk` package to clarify their purpose and improve developer experience. The changes ensure that type checking is only applied when the package is installed, making the code more flexible for users who do not require MCP functionality.
* [`packages/core/src/functional/assertMcpController.ts`](diffhunk://#diff-aa9aebe2421bbd0dd1550507f1a67c8b60e925187d3ca595f8fc8cb768d3de8eL26-R28): Updated the `@ts-ignore` comment for the `client` property to explain that type checking is conditional on the presence of `@modelcontextprotocol/sdk`, catering to users who do not install the package.
* [`packages/core/src/functional/validateMcpController.ts`](diffhunk://#diff-5e3fae321e55035353b3287a65aa52aafb7e34b53ccd560e28 …

feat(core): description about `@ts-ignore`

---

packages/cli/build.config.ts
packages/cli/src/index.test.ts
packages/cli/src/index.ts

Removes the build-time version replacement for the CLI. The version is now directly imported from `package.json` within the `src/index.ts` file.
This simplifies the build configuration and makes the version source more explicit.

fix(cli): Simplify CLI version handling

---

.github/workflows/test.yml

This pull request updates the Node.js versions tested in the GitHub Actions workflow to include the latest version, 24.x.
* [`.github/workflows/test.yml`](diffhunk://#diff-faff1af3d8ff408964a57b2e475f69a6b7c7b71c9978cccc8f471798caac2c88L13-R13): Added Node.js version 24.x to the matrix of versions tested in the CI pipeline.

ci(*): test with node24.x

---

packages/chat/src/examples/shopping/ShoppingChatApplication.tsx

This pull request refactors the `ShoppingChatApplication` component in `packages/chat/src/examples/shopping/ShoppingChatApplication.tsx` to simplify its implementation by removing state management and side effects. The most important changes include converting the component to an `async` function and eliminating the use of `useState` and `useEffect`.
* Converted `ShoppingChatApplication` from a stateful React component to an `async` function, removing the need for `useState` and `useEffect`. This simplifies the component's logic and improves readability. (`[[1]](diffhunk://#diff-0742588351fe4c2a6be54764b634bd9616b8a27cfe8e0642fcf6741046c29b0dL13-R18)`, `[[2]](diffhunk://#diff-0742588351fe4c2a6be54764b634bd9616b8a27cfe8e0642fcf6741046c29b0dL33-R28)`)
* Removed the asynchronous …

qfix(website): fetch swagger on build

---

packages/chat/src/examples/shopping/ShoppingChatApplication.tsx
packages/chat/src/examples/shopping/index.tsx

Extracted `ShoppingChatApplicationSkeleton` for a dedicated loading UI. Integrated `React.Suspense` in the shopping example to display this skeleton during the initial data fetching of the `ShoppingChatApplication`.
This removes the manual loading state handling within `ShoppingChatApplication`, as `HttpLlm.application` is now expected to resolve directly, and Suspense manages the fallback. This change improves user experience and component structure.

fix(website): Use Suspense for shopping chat loading

---

website/package.json

This pull request refactors the build scripts in the `website/package.json` file to improve modularity and maintainability. The changes break down the `prebuild` and `postbuild` scripts into smaller, more focused sub-scripts and use `pnpm` for aggregating their execution.
* Replaced the monolithic `prebuild` script with a modular structure by introducing `prebuild:typedoc` and `prebuild:playground` sub-scripts, and updated the main `prebuild` script to aggregate these using `pnpm`. (`[website/package.jsonL8-R13](diffhunk://#diff-fae242fbf77a8a9d52625664bc36ea12316586f8a716b41137d897a2b7e3df76L8-R13)`)
* Replaced the monolithic `postbuild` script with a modular structure by introducing `postbuild:sitemap` and `postbuild:pagefind` sub-scripts, and updated the main `postbuild` script to …

feat(website): parallelise pre/post build

---

pnpm-lock.yaml
website/app/layout.jsx
website/package.json

This pull request introduces a WebAssembly polyfill for broader browser compatibility and updates the `pagefind` dependency in the `website` project. The most important changes include adding a polyfill script to the `RootLayout` component and adjusting the `pagefind` dependency in `package.json` to resolve potential issues with dependency management.
* [`website/app/layout.jsx`](diffhunk://#diff-b43b1bc0a42db021ecb816f80baa2348806164da1b99c2584eed456d5f7c2e99R98-R100): Added a script to load a WebAssembly polyfill (`polywasm`) dynamically, ensuring compatibility for environments where WebAssembly is not natively supported.
* [`website/package.json`](diffhunk://#diff-fae242fbf77a8a9d52625664bc36ea12316586f8a716b41137d897a2b7e3df76L45): Removed and re-added the `pagefind` dependency, …

feat(website): polyfill WebAssembly for `pagefind`.

---

packages/benchmark/package.json
packages/core/package.json
packages/core/src/Agentica.ts
packages/core/src/MicroAgentica.ts
packages/core/src/constants/AgenticaDefaultPrompt.ts
packages/core/src/structures/IAgenticaVendor.ts
pnpm-lock.yaml
pnpm-workspace.yaml
test/eslint.config.mts
test/package.json
test/src/cli/index.ts
test/src/cli/micro.ts
website/package.json

Special option for `@autobe` supporting.
------------------
This pull request introduces enhancements to the `Agentica` and `MicroAgentica` classes by adding support for concurrency control using semaphores, updates dependencies across multiple packages, and improves the configuration options for limiting concurrent requests. Additionally, it updates the `pnpm-lock.yaml` file to reflect the latest versions of dependencies. Below is a summary of the most important changes grouped by theme.
* Added a `Semaphore` instance to the `Agentica` and `MicroAgentica` classes to manage the number of concurrent requests to the LLM vendor. The semaphore can be shared across agents or configured with a numerical limit. (`packages/core/src/Agentica.ts` …

feat(core): semaphore option for limit request

---

packages/core/src/Agentica.ts
packages/core/src/MicroAgentica.ts
packages/core/src/structures/IAgenticaConfig.ts
packages/core/src/structures/IAgenticaProps.ts
packages/core/src/structures/IMicroAgenticaConfig.ts

This pull request introduces a backoff strategy to handle retries for API calls in the `Agentica` and `MicroAgentica` classes. The changes aim to improve resilience by allowing customizable retry logic when API requests fail. Key updates include adding the backoff strategy logic in the classes and extending the respective configuration interfaces to support this feature.
* `packages/core/src/Agentica.ts` and `packages/core/src/MicroAgentica.ts`: Introduced a retry mechanism with a configurable `backoffStrategy`. If an API call fails, the strategy determines the wait time before retrying. By default, it throws an error if no strategy is provided. [[1]](diffhunk://#diff-fd17ccaf3913505148ef799667fe621b8664f52622f44959be527d79c5109898L286-R304) …

fix(core): add backoffStrategy

---

packages/chat/src/examples/shopping/ShoppingChatApplication.tsx
packages/chat/src/movies/AgenticaChatMovie.tsx
packages/core/src/orchestrate/call.ts
test/src/features/rpc/test_rpc_micro_call.ts
test/src/features/rpc/test_rpc_websocket_call.ts
test/src/features/rpc/test_rpc_websocket_initialize.ts
test/src/features/test_json_parse_error_correction.ts
test/src/features/test_validate_correction.ts

This pull request introduces several changes across multiple files to improve error handling, simplify code, and enhance the shopping chat application. The most significant updates involve replacing the `Suspense`-based asynchronous handling in the shopping chat application with `useState` and `useEffect`, adding support for handling JSON parse errors in the movie chat application, and refactoring tool call handling in the orchestration logic.
* Replaced the `Suspense`-based asynchronous handling with `useState` and `useEffect` for managing the agent's state. This change simplifies the logic and removes the need for the `AsyncAgenticaChatApplication` component. (`packages/chat/src/examples/shopping/ShoppingChatApplication.tsx`, [[1]](diffhunk://#diff-0742588351fe4c2a6be54764b634bd9616b8a27 …

fix(core): exact tool-calling id

---

packages/core/src/factory/events.ts
packages/core/src/orchestrate/internal/completeValidationError.ts
pnpm-lock.yaml
pnpm-workspace.yaml

This pull request introduces a new utility function for handling validation errors and updates several dependencies in the project. The most significant changes include adding the `complementValidationError` function to enhance error descriptions, integrating it into the event creation process, and upgrading key dependencies such as `@samchon/openapi` and `typia`.
* [`packages/core/src/orchestrate/internal/completeValidationError.ts`](diffhunk://#diff-afd285a1775e85740e391e9f1d84881e0161a593318e1f398ff58f13da6866d8R1-R22): Added the `complementValidationError` function to append detailed descriptions to validation errors when the `value` is undefined.
* [`packages/core/src/factory/events.ts`](diffhunk://#diff-3b6bba958553d7f7e9e574a08fc1edab4c3fb4f8fbc49136bf2649f4b11f0d78R25-R26): …

feat(core): `complementValidationError` for `undefined` values.

---

packages/core/src/MicroAgentica.ts

This pull request introduces a conditional check to ensure that the `describe` method is only executed when the `executor.describe` property in the configuration is not `null`. This change enhances the robustness of the `MicroAgentica` class by preventing unnecessary or invalid calls to the `describe` function.
* [`packages/core/src/MicroAgentica.ts`](diffhunk://#diff-d0b41ca18164569e2f6b061dcac423715cca7eaa85200c4c1ed410f179850b28L169-R169): Updated the conditional in the `if` statement to include a check for `this.props.config?.executor?.describe !== null` before calling the `describe` function.

fix(core): ensure executor description is not null before calling decribe

---

packages/core/prompts/execute.md

해병문학 시전 금지.
이대로 함수를 호출해도 되겠습니까에 대한 의문이 있는 것을 표현해도 되는지에 대해 심판해주실 수 있는지에 대해 발언하는 것이 무례하지는 않은지에 대해 판정을 해 주실 수 있는지를 감히 제가 알아도 되겠습니까?
---
This pull request introduces a new critical guideline to the function calling process in `packages/core/prompts/execute.md`. The main update is a section that instructs assistants to execute functions immediately when all required information is available, without asking for permission or explaining their plan, except when explicitly instructed otherwise.
Function execution process update:
* Added a new "CRITICAL: Immediate Function Execution" section, emphasizing that assistants should call functions right away when ready, and should not seek permission, explain their plan, or request confirmation before execution.
* Clarified that exceptions to this rule …

feat(core): function calling instruction about immediate execution.

---

packages/core/src/orchestrate/call.ts
packages/core/src/orchestrate/select.ts
test/src/features/rpc/test_rpc_websocket_call.ts
test/src/features/rpc/test_rpc_websocket_initialize.ts
test/src/features/test_base_event.ts
test/src/features/test_base_work.ts
test/src/features/test_call_streaming_base.ts
test/src/features/test_select_streaming_base.ts

This pull request refactors how assistant message events are handled during streaming completions in both the `call` and `select` orchestration flows. It introduces a more robust mechanism for managing partial message content and streaming updates using a multi-producer, single-consumer (MPSC) queue. The assistant message event dispatch logic is now unified and incremental, leading to more accurate event handling and improved test coverage. Several related tests have been updated to reflect these changes.
**Streaming and Assistant Message Handling Improvements:**
* Replaced previous chunk aggregation and event dispatch logic in `call.ts` and `select.ts` with a new streaming approach using `MPSC`, enabling incremental assistant message events as content arrives. This ensures events are …

feat(core): refactor call and select functions to utilize MPSC for streaming context management

---

packages/core/eslint.config.mts
packages/core/src/events/AgenticaJsonParseErrorEvent.ts
packages/core/src/events/AgenticaValidateEvent.ts
packages/core/src/factory/events.ts
packages/core/src/json/IAgenticaEventJson.ts
packages/core/src/orchestrate/call.ts
packages/core/src/orchestrate/select.ts
packages/core/src/utils/AssistantMessageEmptyError.ts

This pull request makes minor changes to the retry logic in the orchestration functions, ensuring that all retries are now hardcoded to a single attempt rather than using the configurable value. Additionally, there is a small formatting fix in one of the function bodies.
Retry logic changes:
* In both the `call` function (`packages/core/src/orchestrate/call.ts`) and the `step` function (`packages/core/src/orchestrate/select.ts`), the retry count is now hardcoded to `1` instead of using `ctx.config?.retry` or a constant, simplifying the retry behavior. [[1]](diffhunk://#diff-fab757df7c77323a0efe9872a53054b76585edada69dc8515773aa7b598a023eL38-R38) [[2]](diffhunk://#diff-d08a1ba455bc31708d65ef9948166f391bad9eff3ebf97d754e428530328734cL98-R98)
Code formatting:
* Added a missing semicolon …

feat(core): retry only one time for `openrouter`
