src/chatgpt/ChatGptExecuteFunctionAgent.ts
src/structures/IWrtnAgentController.ts

This pull request includes changes to enhance the execution logic of function calls in the `ChatGptExecuteFunctionAgent` and `IWrtnAgentController` namespaces. The most important changes involve improving the handling of function execution and updating the parameter types for better clarity and flexibility.
Improvements to function execution handling:
* [`src/chatgpt/ChatGptExecuteFunctionAgent.ts`](diffhunk://#diff-b95986f1f703ccb19c962c373e590bf2ae6a2f5a62aa0a8b06874dcfe152898eL268-R277): Modified the `execute` method to handle cases where `call.operation.controller.execute` is not a function by using a conditional check. This ensures that the correct execution path is taken based on the type of `execute`.
Updates to parameter types:
* …

Direct executor of class controller

---

README.md

This pull request includes significant updates to the `README.md` file to improve clarity and provide additional setup and usage instructions for the `@wrtnlabs/agent` library. The most important changes include rebranding the library name, enhancing the description, adding setup instructions, and explaining the agent strategy and validation feedback principles.
* **Library Rebranding and Description Enhancement**:
- Updated the library name to `@wrtnlabs/agent` and refined the description to emphasize its specialization in LLM function calling and its applications in AI chatbot development and multi-agent orchestration.
* **Setup Instructions**:
- Added a new "Setup" section with detailed instructions on installing the required packages (`@wrtnlabs/agent`, `@samchon/openapi`, and …

Add principles chapter on README

---

README.md

This pull request includes several updates to the `README.md` file to improve clarity and provide additional information about future plans for the `@wrtnlabs/agent` project. The most important changes include correcting headings, enhancing descriptions for validation feedback, and adding a new roadmap section.
Documentation improvements:
* Corrected the heading from "Multi-agent Orchestration" to "Multi Agent Orchestration" for consistency.
* Improved the description of the validation feedback strategy to emphasize the ideal LLM function calling achieved by combining typia's runtime validator with `@wrtnlabs/agent`.
Additional information:
* Added a new "Roadmap" section outlining future plans, including guide documents, a playground website, a WebSocket module, and support for multiple …

The new chapter Roadmap on README

---

package.json
src/rpc/IWrtnAgentRpcListener.ts
src/rpc/WrtnAgentRpcService.ts
test/features/test_base_websocket.ts
test/features/test_websocket.ts
test/index.ts

This pull request includes several changes to the `@wrtnlabs/agent` package. The main updates involve adding a new initialization event to the AI agent, enhancing the WebSocket test setup, and simplifying the test index file. Additionally, the package version has been incremented.
* [`src/rpc/IWrtnAgentRpcListener.ts`](diffhunk://#diff-71ea73acdd23053804f08336a293db92d15b94fe0d1576718b980fef52f0385dR65-R74): Added a new `initialize` method to the `IWrtnAgentRpcListener` interface to handle initialization events from the AI agent server to the client.
* [`src/rpc/WrtnAgentRpcService.ts`](diffhunk://#diff-301cd8173845997a3cbdcc077664cdc119e56564ad845ed918f2391db800cac9R64): Updated the `WrtnAgentRpcService` class to listen for the `initialize` event and call the corresponding listener …

`IWrtnAgentRpcListener.initialize()` and test websocket module.

---

package.json
packages/agent/package.json

Fix: ci page build error

---

.github/workflows/build.yml
packages/agent/.gitignore
packages/agent/package.json
packages/agent/src/WrtnAgent.ts
packages/agent/src/benchmark/select/IWrtnAgentSelectBenchmarkEvent.ts
packages/agent/src/benchmark/select/IWrtnAgentSelectBenchmarkResult.ts
packages/agent/src/benchmark/select/IWrtnAgentSelectBenchmarkScenario.ts
packages/agent/src/benchmark/select/WrtnAgentSelectBenchmark.ts
packages/agent/src/benchmark/select/internal/WrtnAgentSelectBenchmarkReporter.ts
packages/agent/src/internal/MathUtil.ts
packages/agent/src/internal/TokenUsageComputer.ts
packages/agent/src/module.ts
packages/agent/src/structures/IWrtnAgentContext.ts
packages/agent/src/structures/IWrtnAgentPrompt.ts
packages/agent/test/features/test_benchmark_select.ts

This pull request introduces several enhancements and new features to the `packages/agent` module, including updates to versioning, new imports, and the addition of benchmark-related classes and interfaces. The most important changes include updating the package version, adding new imports, refactoring the `conversate` method, and introducing new benchmark-related functionality.
* [`packages/agent/package.json`](diffhunk://#diff-f0f4adde46deb8e106c88cfb5dbf48155b8261ff0d73ada3429381a40e9bb3baL3-R3): Updated the package version from `0.2.0` to `0.3.0` and fixed a typo in the `dev` script. [[1]](diffhunk://#diff-f0f4adde46deb8e106c88cfb5dbf48155b8261ff0d73ada3429381a40e9bb3baL3-R3) [[2]](diffhunk://#diff-f0f4adde46deb8e106c88cfb5dbf48155b8261ff0d73ada3429381a40e9bb3baL14-R14)
* …

LLM function selection benchmark

---

packages/agent/package.json
packages/agent/src/structures/IWrtnAgentController.ts

This pull request includes updates to the `packages/agent` module, focusing on versioning and enhancing the `IWrtnAgentController` interface. The most important changes include updating the package version and modifying the `execute` method to support a more flexible callback function structure.
Version update:
* [`packages/agent/package.json`](diffhunk://#diff-f0f4adde46deb8e106c88cfb5dbf48155b8261ff0d73ada3429381a40e9bb3baL3-R3): Updated the version from `0.4.0` to `0.4.1`.
Enhancements to `IWrtnAgentController` interface:
* [`packages/agent/src/structures/IWrtnAgentController.ts`](diffhunk://#diff-b74188677362aa20b1e57f5113f2f92dcdc3d99a375921e552ae9b7dc2f3fab2L90-R96): Refactored the `execute` method to accept either an object or a callback function with schema and arguments …

Fix `IWrtnAgentController.IClass.execute` type.

---

packages/agent/src/benchmark/call/WrtnAgentCallBenchmark.ts
packages/agent/src/benchmark/common/WrtnAgentBenchmarkPredicator.ts
packages/agent/test/features/test_benchmark_predicator.ts
packages/agent/test/features/test_benchmark_predicator_simple_allof.ts

I removed the allOf test case and add additional comment

fix(#45): wrong configured benchmark WrtnAgentBenchmarkPredicator success implementation

---

packages/core/src/chatgpt/ChatGptSelectFunctionAgent.ts

change `packages/core/src/chatgpt/ChatGptSElectFunctionAgent.ts` for inject user custom prompt

fix: select prompt can change to provided by user

---

README.md
packages/rpc/README.md

This pull request includes significant updates to the `README.md` file to provide detailed instructions for setting up and using the `@agentica/rpc` package. The changes include adding a new section for NestJS applications, updating installation instructions, and providing examples for API controllers and SDK generation.
* [`README.md`](diffhunk://#diff-0c1ed2e514cbc8e9e15cde8b6a0944a6a02f6e9ad21242bf0d70c08d73f8eda2R118-R221): Added a new section for NestJS applications, including subsections for Bootstrap, API Controller, and Software Development Kit. This provides detailed steps for integrating `@agentica` with NestJS using Nestia.
* [`packages/rpc/README.md`](diffhunk://#diff-0c1ed2e514cbc8e9e15cde8b6a0944a6a02f6e9ad21242bf0d70c08d73f8eda2L41-R55): Updated installation instructions to …

Guide NestJS WebSocket integration

---

packages/core/README.md

fix: typo in @agentica/core

---

package.json
packages/chat/src/examples/index.tsx

This pull request includes changes to the `package.json` file and the `packages/chat/src/examples/index.tsx` file to update the version and improve the URLs for different sections. The most important changes are:
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L4-R4): Updated the version from `0.10.1` to `0.10.2`.
* [`packages/chat/src/examples/index.tsx`](diffhunk://#diff-d749a72848abc30de40184ece1042d1d160d9945e9a748411764a6cb2c65dbefL52-R52): Changed the `href` attribute for the "Agentica Playground" section from `./playground.html` to `./playground/`.
* [`packages/chat/src/examples/index.tsx`](diffhunk://#diff-d749a72848abc30de40184ece1042d1d160d9945e9a748411764a6cb2c65dbefL67-R67): Changed the `href` attribute for the "Shopping AI …

Fix examples link

---

package.json
packages/rpc/package.json

This pull request includes updates to the version numbers of dependencies and the package version in the `package.json` files.
Version updates:
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L4-R4): Updated the package version from `0.10.3` to `0.10.4`.
Dependency updates:
* [`packages/rpc/package.json`](diffhunk://#diff-68aaf91f74a0ea0d392cd7e8a0bd6de0a8cff7abdd251b6b9875111556003650L43): Removed the dependency on `@samchon/shopping-api` version `^0.15.0`.
* [`packages/rpc/package.json`](diffhunk://#diff-68aaf91f74a0ea0d392cd7e8a0bd6de0a8cff7abdd251b6b9875111556003650R51): Added the dependency on `@samchon/shopping-api` version `^0.16.0`.

Fix wrong dependency

---

website/content/docs/plugins/pg-vector-selector.mdx

Docs: pg vector plguin

---

packages/cli/package.json
packages/cli/src/bases/Connector.ts
packages/cli/src/bases/Package.ts
packages/cli/src/bases/Tsconfig.ts
packages/cli/src/executable/AgenticaStart.ts
packages/cli/src/index.ts
packages/cli/src/utils/capitalize.ts
packages/cli/src/utils/createProjectDirectory.ts
packages/cli/src/utils/getNpmPackages.ts
packages/cli/src/utils/getQuestions.ts
packages/cli/tsconfig.json

- Write the code to proceed with the default setting of the Agentica package with the command `npx agentica start <directory>`.
- Currently, only package manager selection, project type selection, and controller embedding can be performed.
- In the future, server additional functions such as NestJS, NodeJS, and React should be provided.

feat: Agentica CLI

---

packages/core/src/structures/IAgenticaProps.ts
packages/core/src/structures/IAgenticaSystemPrompt.ts

Very small PR.
Replace default prompt link from nestia to agentica.

replace nestia link to agentica

---

website/content/docs/websocket/index.mdx
website/content/docs/websocket/nestjs.mdx

This pull request includes updates to the documentation for setting up NodeJS, NestJS, and client applications with various package managers. The changes add support for `npm`, `pnpm`, and `yarn` in the setup instructions, and provide additional context on the required packages and their purposes.
* [`website/content/docs/websocket/index.mdx`](diffhunk://#diff-77b071a167492a27529e9c9bc5b0a69f9ee3def5d56ee7de0cc6f43f4ea534abR107-R207): Added setup instructions for `npm`, `pnpm`, and `yarn` for NodeJS, NestJS, and client applications. Included explanations of required packages such as `@agentica/core`, `@samchon/openapi`, `typia`, `@agentica/rpc`, and `tgrid`.
* [`website/content/docs/websocket/nestjs.mdx`](diffhunk://#diff-20fa5513235980c756a5674d492ee602fa4e6e81b732594d9184a25d60d34f3eL47- …

WebSocket setup summary.

---

website/app/layout.jsx
website/content/docs/concepts/function-calling.mdx
website/content/docs/core/event.mdx

This pull request includes several updates to the documentation and meta tags in the `website` directory. The changes primarily focus on providing more detailed explanations of the `Agentica` instance and its events, as well as updating URLs in meta tags for better social media integration.
* [`website/content/docs/concepts/function-calling.mdx`](diffhunk://#diff-0e5107784de67352aca363b2d8c11613d81be3ff7987d9760e91a1d6dbfca49fR120-R130): Added detailed explanations about validation feedback strategies for LLM providers and restriction properties of JSON schema.
* [`website/content/docs/core/event.mdx`](diffhunk://#diff-54f3586de8e38e480346f32a7c1c56c00da394176a2338975a39ee4410d220f7R79-R88): Expanded documentation on how to use the `Agentica` instance, including details on starting the …

Event and function calling chapters

---

website/content/docs/core/history.mdx

This pull request includes several changes to the `website/content/docs/core/history.mdx` file, primarily focusing on improving the documentation of the `Agentica` library. The changes include adding detailed descriptions of various types of prompt histories and making minor code adjustments.
Documentation improvements:
* Added detailed descriptions for `AgenticaPrompt.Text`, `AgenticaPrompt.Select`, `AgenticaPrompt.Execute`, and `AgenticaPrompt.Describe` types, explaining their roles and how they can be managed to reduce LLM token costs. [[1]](diffhunk://#diff-1966c23d28c4170cef07bdd54a00aa21fae5914f517b98366a3731e64656b828R95-R98) [[2]](diffhunk://#diff-1966c23d28c4170cef07bdd54a00aa21fae5914f517b98366a3731e64656b828R147-R153) [[3]](diffhunk://#diff-1966c23d28c4170cef07bdd54a00aa21fae591 …

Completion of core library contents

---

.github/workflows/website.yml
website/app/_components/landing/ChatBubble.tsx
website/app/_components/landing/WelcomeSection.tsx
website/app/_constants/landing.ts

This pull request includes updates to the website's build process, code cleanup, and improvements to the chat example messages. The most important changes are listed below:
* [`.github/workflows/website.yml`](diffhunk://#diff-c7731b29de71fca225e1dfac88ebe31975a4cd9759ab13e91d86eeadafbddc10L25-R25): Simplified the build process by replacing `npm install` and `npm run build` with a single `pnpm run build` command.
* [`website/app/_components/landing/ChatBubble.tsx`](diffhunk://#diff-cf2bc3f065563308620bc9b29e7c698638de5acdd3e7d1bd812e8e6d79659cd9L38-R38): Commented out unused `isFuncCall` variable and related JSX code. [[1]](diffhunk://#diff-cf2bc3f065563308620bc9b29e7c698638de5acdd3e7d1bd812e8e6d79659cd9L38-R38) [[2]](diffhunk://#diff-cf2bc3f065563308620bc9b29e7c698638de5acdd3e7d1bd812e8e6d …

Fix some errors and contents

---

.gitignore
package.json
pnpm-lock.yaml

this project is missing lockfile.

chore: add pnpm lockfile 

---

packages/cli/src/executable/AgenticaStart.ts
packages/cli/src/functional/AgenticaStarter.ts
packages/cli/src/structures/IAgenticaStart.ts
packages/cli/src/utils/getQuestions.ts

First, I moved AgenticaStarter to the functional directory and getQuestion to the util directory.
Second, remove unused getQuestion function(The existing getQuestion function in the util directory didn't have any references linked to it) and move getQuestion to util directory.(In other words, I replaced the existing one)
---
This pull request includes significant refactoring and restructuring of the `AgenticaStart` functionality in the CLI package. The changes primarily focus on modularizing the code, improving maintainability, and centralizing logic related to project setup and configuration.
* [`packages/cli/src/executable/AgenticaStart.ts`](diffhunk://#diff-a96f3ceac5d81d41e64a77cf1f4e42889aba41e66ac7f6d3475782be7f379b7aL2-R11): Removed multiple imports and internal logic related to …

refactor(cli): Modularize each function and remove unused code

---

website/content/docs/core/index.mdx
website/content/docs/roadmap.mdx

This pull request includes updates to the `website/content/docs` to enhance the documentation for `@agentica/core` and outline the future roadmap for the library. The changes focus on simplifying the explanation of the library's capabilities and introducing new features and support plans.
Documentation improvements:
* [`website/content/docs/core/index.mdx`](diffhunk://#diff-34584eba8a785857005664eb5a9afbc33d5a3d62c4a3e73f76c8bce90d7b5916L22-R22): Simplified the description of `@agentica/core` by emphasizing the ease of building an Agentic AI chatbot with Swagger documents or TypeScript class types, without requiring complex agent workflows.
Roadmap additions:
* [`website/content/docs/roadmap.mdx`](diffhunk://#diff-5319517a72645044dc0366592c1263c3d1e2a1132a6970047e88021e858e9939R4-R30): …

Roadmap chapter

---

packages/cli/package.json
packages/cli/rslib.config.ts
packages/cli/src/index.ts
pnpm-lock.yaml

I discussed with samchon, rslib/rspack is good bundler.
Also, this agentica/cli is cli(of course), so smaller is better.
Here we can build cli with minified executable code.

ci(cli): build with rslib

---

packages/cli/src/executable/AgenticaStart.ts
packages/cli/src/functional/AgenticaStarter.ts
packages/cli/src/utils/getQuestions.ts

- add `start` CLI logic about react template
- no code generation or modification in react files.

feat(cli): add React Template for project type

---

website/content/tutorial/_meta.ts
website/content/tutorial/enterprise/_meta.ts
website/content/tutorial/enterprise/shopping.mdx
website/content/tutorial/productivity/_meta.ts

This pull request introduces significant updates to the `website/content/tutorial` section, primarily focusing on the addition of enterprise-level content and examples. The most important changes include adding a new enterprise section, creating meta information for the enterprise tutorial, and adding a comprehensive example of a shopping AI chatbot.
* [`website/content/tutorial/_meta.ts`](diffhunk://#diff-2ba1f27d9ff5e2e8a22fb36556b54411e124b6ef4c7e1ec727339fd03b1194d3R15-R20): Added a new "Enterprise" section with its title and theme settings.
* [`website/content/tutorial/enterprise/_meta.ts`](diffhunk://#diff-fb286cf0436bf411a6daf01a61b54b7789a8e59adf2c39e7c450d6738d75d092R1-R6): Created meta information for the enterprise tutorial, including a shopping mall title.
* …

enterprise tutorial

---

website/content/tutorial/coding/_meta.ts
website/content/tutorial/coding/github.mdx
website/content/tutorial/productivity/_meta.ts
website/content/tutorial/productivity/arxiv.mdx
website/content/tutorial/productivity/gmail.mdx
website/content/tutorial/productivity/google-calendar.mdx
website/content/tutorial/productivity/google-image.mdx
website/content/tutorial/productivity/google-search.mdx
website/content/tutorial/productivity/notion.mdx
website/content/tutorial/productivity/slack.mdx

This pull request includes significant updates to the tutorials for setting up various agents using Agentica CLI. The changes streamline the setup process, introduce new tutorials, and enhance existing ones. The most important changes are summarized below.
* **Github Agent Tutorial**:
- Simplified the setup process using the Agentica CLI. Users can now launch the setup wizard with a single command, which guides them through the installation and configuration steps.
- Updated the code to use a more concise application setup for the Github Agent.
- Improved instructions for setting up Github API credentials and environment variables.
* **New RAG Agent Tutorial**:
- Added a new tutorial for setting up a Retrieval-Augmented Generation (RAG) Agent using Agentica. This tutorial includes …

docs(website) document unification

---

CONTRIBUTING.md
README.md

1. link contirubing file in `README.md`
2. modify detail in `CONTRIBUTING.md`
---
My English isn't great
Most of them involve using a translator.
So please give me your feedback!

docs: update contributing guide document

---

website/content/docs/concepts/compiler-driven-development.mdx

you can merge it without asking me

fix(typo): methodology

---

.github/workflows/build-and-publish-dry-run.yml
.github/workflows/lint-check.yml
.github/workflows/release.yml
.github/workflows/spell-check.yml
.github/workflows/test.yml
.github/workflows/website.yml

pin actions SHA using [`pinact`](https://github.com/suzuki-shunsuke/pinact)
This enhances the security
https://www.stepsecurity.io/blog/harden-runner-detection-tj-actions-changed-files-action-is-compromised
https://semgrep.dev/blog/2025/popular-github-action-tj-actionschanged-files-is-compromised/

feat(ci): pin action SHA

---

website/content/docs/concepts/compiler-driven-development.mdx
website/content/snippets/BbsArticleControllerSnippet.mdx
website/content/snippets/BbsArticleServiceSnippet.mdx
website/content/snippets/ClassValidatorSnippet.mdx
website/content/snippets/IBbsArticleSnippet.mdx
website/content/snippets/KotlinSpringSnippet.mdx
website/content/snippets/LlmApplicationExampleSnippet.mdx
website/content/snippets/LlmApplicationJavaScriptSnippet.mdx
website/content/snippets/PhpLaravelSnippet.mdx
website/content/snippets/PythonDjangoSnippet.mdx
website/content/snippets/PythonFastApiSnippet.mdx

This pull request includes significant updates to the `compiler-driven-development.mdx` document, focusing on enhancing clarity and adding new examples and snippets to illustrate concepts. The most important changes include adding new code snippets, refining explanations, and updating the sections on backend development frameworks.
* Added new code snippets: `ClassValidatorSnippet`, `LlmApplicationExampleSnippet`, `LlmApplicationJavaScriptSnippet`, `BbsArticleControllerSnippet`, `BbsArticleServiceSnippet`, and `IBbsArticleSnippet`. These snippets provide additional examples to support the explanations.
* Introduced a new `Tabs` section under "TypeScript Class" to include multiple code examples and a playground link for better understanding.
* Improved the explanation of the LLM function …

Complete CDD

---

.github/workflows/build-and-publish-dry-run.yml
package.json

Update references to the script in GitHub workflow and package.json to use the new plural form for consistency.

refactor: rename build:package script to build:packages

---

.github/workflows/test.yml
package.json

Add root test command and specialized test scripts for e2e and packages
to improve testing workflow organization in the monorepo.

feat: add test scripts to package.json and add test script in `test.yml`

---

website/content/tutorial/index.mdx

- Update Agentica Tutorial Getting Started page.
- Add Youtube Video that how to use agentica cli.

docs(website): Update Agentica Tutorial Getting Started using cli

---

README.md
website/app/layout.jsx
website/content/docs/concepts/_meta.ts
website/content/docs/index.mdx

This pull request includes updates to the documentation and layout of the Agentica project. The most important changes include adding new badges to the `README.md`, updating the layout to include new scripts, and ensuring consistency in the documentation links.
Documentation updates:
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R8-R9): Added new badges for Guide Documents and Gurubase.
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L56-R59): Reordered the Concepts section for better readability.
Layout updates:
* [`website/app/layout.jsx`](diffhunk://#diff-b43b1bc0a42db021ecb816f80baa2348806164da1b99c2584eed456d5f7c2e99L2-R2): Added scripts for Clarity and Gurubase widgets to the layout. …

Add gurubase chatbot

---

website/content/tutorial/index.mdx

- modify tutorial video location

docs(website): modify_location_of_agentica_tutorial_video

---

packages/cli/src/commands/start.ts
packages/cli/src/packages.test.ts
packages/cli/src/packages.ts

feat(cli):Detect package manager

---

.github/workflows/build-and-publish-dry-run.yml
packages/benchmark/package.json
packages/chat/package.json
packages/cli/package.json
packages/core/package.json
packages/pg-vector-selector/package.json
packages/rpc/package.json

This pull request includes changes to the build and publish processes across multiple packages. The most significant changes involve modifying the `prepublishOnly` script to `prepack` in various `package.json` files and updating the build and publish steps in the GitHub Actions workflow.
Changes to GitHub Actions workflow:
* [`.github/workflows/build-and-publish-dry-run.yml`](diffhunk://#diff-83557b83c2cfceae0ea7576350bcc8d05a72ad0803e2265bd64527312df08ac8L13-R13): Simplified the build and publish steps by removing the expansion of `publishConfig` and updating the `pnpm dlx` command.
Changes to `package.json` scripts:
* [`packages/benchmark/package.json`](diffhunk://#diff-03d34ead8faa24fcf5b6d74b52eaf57db4400f375b60698e3f5024e28b29b0e1L44-R44): Changed the `prepublishOnly` script to …

chore(*): prepublish -> prepack && use pkg.pr.new builtin pnpm support

---

packages/rpc/README.md
packages/rpc/package.json
packages/rpc/rollup.config.js
packages/rpc/src/AgenticaRpcService.ts
packages/rpc/src/IAgenticaRpcListener.ts
packages/rpc/src/IAgenticaRpcService.ts
packages/rpc/src/index.ts
packages/rpc/tsconfig.json
packages/rpc/typedoc.json

This pull request includes various updates and improvements to the `@agentica/rpc` package, focusing on documentation enhancements, type improvements, and configuration updates. The most important changes are grouped into documentation updates, type improvements, and configuration updates.
* Added a conceptual diagram to the `README.md` to provide a visual overview of the `agentica` system.
* Improved the readability and formatting of the `README.md` by adding spacing and skipping ESLint checks where necessary. [[1]](diffhunk://#diff-0c1ed2e514cbc8e9e15cde8b6a0944a6a02f6e9ad21242bf0d70c08d73f8eda2L35-R39) [[2]](diffhunk://#diff-0c1ed2e514cbc8e9e15cde8b6a0944a6a02f6e9ad21242bf0d70c08d73f8eda2R58-R60) [[3]](diffhunk://#diff-0c1ed2e514cbc8e9e15cde8b6a0944a6a02f6e9ad21242bf0d70c08d73f8eda2R90) …

fix(rpc): lint fix

---

website/content/tutorial/productivity/_meta.ts
website/content/tutorial/productivity/youtube-search.mdx

This pull request includes updates to the `website/content/tutorial/productivity` section to add a new tutorial for setting up a Youtube Search Agent using Agentica. The changes include adding metadata for the new tutorial and a detailed markdown file with instructions.
* [`website/content/tutorial/productivity/_meta.ts`](diffhunk://#diff-f13443c45f2e36e56f4b70ac78943b7577319e836c64ef9c6c63b603026b42e2R14): Added "youtube-search" to the list of tutorials.
* [`website/content/tutorial/productivity/youtube-search.mdx`](diffhunk://#diff-47a93714d61fc78d1e511f0480162cc9abc69120da96720890d45132ca472d42R1-R100): Added a new markdown file with a comprehensive tutorial on setting up a Youtube Search Agent using the Agentica CLI, including setup instructions, generated code overview, environment …

 docs(website): add youtube search toutorial

---

packages/cli/src/commands/start.ts

- Add the help comment to Agentica cli's connector question.

fix(cli): add the help comment to cli connector question

---

packages/cli/build.config.ts

I forgot to add banner option here actually!

fix(cli): add banner option

---

.vscode/settings.json

@sunrabbit123 
Configured base on the guide
https://github.com/antfu/eslint-config#ide-support-auto-fix-on-save
I'm not a vscode user. If you need to modify it, please modify it !
cc: @samchon

chore: eslint config for vscode

---

packages/core/src/functional/assertHttpLlmApplication.ts
packages/core/src/functional/validateHttpLlmApplication.ts

Related issue: https://github.com/wrtnlabs/agentica/issues/253
-----------
This pull request includes several updates across multiple packages, primarily focusing on version bumps and dependency updates. The most important changes include updating the version numbers of various packages, synchronizing dependencies, and modifying some TypeScript functions for better type assertion.
* Updated the version numbers of all packages from `0.13.2` to `0.13.3` to reflect the new release. (`[[1]](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L3-R3)`, `[[2]](diffhunk://#diff-03d34ead8faa24fcf5b6d74b52eaf57db4400f375b60698e3f5024e28b29b0e1L3-R3)`, `[[3]](diffhunk://#diff-162e61feb520f86e5b6de240f53beb7e78cc2846c0659c041848042f089a658cL2-R15)`, …

feat(core): bump up dependencies and change http application creator type

---

website/content/docs/core/facade.mdx
website/content/docs/core/index.mdx
website/content/docs/plugins/benchmark.mdx
website/content/snippets/AgenticaExampleActualSnippet.mdx
website/content/snippets/AgenticaExamplePseudoSnippet.mdx
website/content/tutorial/coding/swagger.mdx
website/content/tutorial/index.mdx

This pull request includes several changes to various documentation files in the `website/content` directory. The changes primarily involve updating import statements and modifying the `application` function calls to use `assertHttpLlmApplication` instead of `HttpLlm.application`. Additionally, headers with authorization tokens have been added to connection configurations.
Key changes include:
* Updated import statements to include `assertHttpLlmApplication` and removed `HttpLlm` and `OpenApi` imports in multiple files. [[1]](diffhunk://#diff-34584eba8a785857005664eb5a9afbc33d5a3d62c4a3e73f76c8bce90d7b5916L22-L24) [[2]](diffhunk://#diff-7a31aeb84e1acaf5cade10ea08d0bd78cfefe08d18ebe0660ea6e597b37a1a7eL2-R2) [[3]](diffhunk://#diff-8733e18f747b30317863f49037e9cc44c8c059e2125e7cf32d64e28022f8b …

doc(website): documentation of #253

---

packages/cli/build.config.ts

Reverts wrtnlabs/agentica#283
becasue of:
- ✅ **CLI**: A small application made of small functions.  
→ Easily controllable with unit/integration tests.  
→ Use a bundler to remove unnecessary code.
- 📦 **Libraries & large apps (e.g., websites)**:  
→ May be hard to control with tests.  
→ Keep source maps for better debugging.
- 🌐 **Webpages**:  
→ Since we deploy them ourselves, bundling is acceptable.
---
anyone can merge it! good night!

Revert(cli): "feat(cli): add map file for trace error"

---

packages/cli/src/commands/start.ts
packages/cli/src/packages.ts

- for the npm build error in cli template, add prepare logic to `start` cli

fix(cli): add runCommand function and prepare script

---

packages/cli/src/commands/start.ts

- React not use `prepare` script. so move that logic.

fix(cli): move the prepare logic

---

packages/chat/src/examples/shopping/index.tsx
packages/chat/src/examples/uploader/AgenticaChatPlaygroundApplication.tsx
packages/chat/src/movies/AgenticaChatMovie.tsx
packages/core/src/Agentica.ts
packages/core/src/orchestrate/call.ts
packages/core/src/orchestrate/describe.ts
packages/core/src/orchestrate/initialize.ts
packages/core/src/orchestrate/internal/selectFunction.ts
packages/pg-vector-selector/src/AgenticaPgVectorSelector.ts

This pull request includes several changes aimed at improving error handling by adding `.catch(() => {})` to various asynchronous operations. Additionally, there is a minor logging enhancement. The most important changes include modifications to event dispatching and user interaction handlers.
Error handling improvements:
* [`packages/chat/src/examples/shopping/index.tsx`](diffhunk://#diff-501abb0a14e3fd296b810061ce0a259f8042eab25be77d89d1253506b80fe73bL171-R172): Updated `onClick` handlers to include `.catch(() => {})` for `startChatApplication` to prevent unhandled promise rejections.
* [`packages/chat/src/examples/uploader/AgenticaChatPlaygroundApplication.tsx`](diffhunk://#diff-d9d9b3a8e9fc197f77786dca26b0189df2cebfa0b4e99574adf1164319504cb4L293-R293): Added `.catch(() => {})` to the …

fix(chat): wrong void statements before async function.

---

packages/chat/src/examples/uploader/AgenticaChatPlaygroundApplication.tsx
packages/chat/src/movies/AgenticaChatMovie.tsx

This pull request includes changes to improve the consistency and reliability of event handling in the `AgenticaChatUploaderApplication` and `AgenticaChatMovie` components by modifying the `onClick` handlers.
Event handling improvements:
* [`packages/chat/src/examples/uploader/AgenticaChatPlaygroundApplication.tsx`](diffhunk://#diff-d9d9b3a8e9fc197f77786dca26b0189df2cebfa0b4e99574adf1164319504cb4L293-R293): Changed the `onClick` handler in the `AgenticaChatUploaderApplication` component to use an arrow function for better consistency and to avoid potential issues with `this` context.
* [`packages/chat/src/movies/AgenticaChatMovie.tsx`](diffhunk://#diff-36e4cfdf39ba62466600231cde9f36e7ea1723fd1b39aab8e6915d255c3ed45fL254-R254): Updated the `onClick` handlers in the `AgenticaChatMovie` …

fix(chat): wrong void statement again

---

packages/core/src/index.ts
packages/rpc/src/IMicroAgenticaRpcListener.ts
packages/rpc/src/MicroAgenticaRpcService.ts
packages/rpc/src/index.ts
test/src/features/rpc/test_rpc_micro_call.ts

This pull request introduces a new RPC interface and service for handling AI agent interactions via WebSockets. The key changes include adding new export statements, defining a new RPC listener interface, creating a new RPC service class, and updating the test suite to cover these new functionalities.
* [`packages/rpc/src/IMicroAgenticaRpcListener.ts`](diffhunk://#diff-af0aad52e940c1ee1b2f6f182d832f33bec15b54a3eb6fd282576596bd5a3a69R1-R93): Added a new interface `IMicroAgenticaRpcListener` that defines event listener functions for handling AI agent events such as `describe`, `text`, `call`, and `execute`.
* [`packages/rpc/src/MicroAgenticaRpcService.ts`](diffhunk://#diff-d5fd5b8db0f20fe665e211a7d031821a1bcc62f4f82f809ef849aa86e089d43eR1-R113): Introduced the `MicroAgenticaRpcService` …

feat(rpc): support `MicroAgentica in WebSocket

---

website/content/docs/concepts/function-calling.mdx
website/content/docs/core/_meta.ts
website/content/docs/core/event.mdx
website/content/docs/core/facade.mdx
website/content/docs/core/index.mdx
website/content/docs/core/micro.mdx
website/content/snippets/MicroAgenticaSnippet.mdx

This pull request to the documentation of the `Agentica` library includes several updates and additions to improve clarity and accuracy. The most significant changes include correcting statistics in the `function-calling.mdx` file, updating import statements and content in various documentation files, and adding a new guide document for `MicroAgentica`.
* [`website/content/docs/concepts/function-calling.mdx`](diffhunk://#diff-0e5107784de67352aca363b2d8c11613d81be3ff7987d9760e91a1d6dbfca49fL90-R96): Corrected the success rate statistics for `gpt-4o-mini` and updated the description of the validation feedback strategy.
* [`website/content/docs/core/_meta.ts`](diffhunk://#diff-bcdc79cbd8898a442ca60208fbb744188c4833d47cc771ce1c520dd0490ecbc7L5-R9): Updated the meta record to include "Micro …

doc(core): concised description about `MicroAgentica`

---

README.md

This pull request includes updates to the `README.md` file to enhance its presentation and correct a minor typo.
go to [readme branch](https://github.com/wrtnlabs/agentica/tree/readme) and check it out
Enhancements to presentation:
* Added a new badge for the MIT license to the badges section.
Typo correction:
* Corrected the spelling of "Playground" in the links section.

docs: update readme ( add mit badge/fix typo)

---

README.md

It's simple, but I found a typo in the readme and fix it :)

docs(readme): typos

---

benchmark/pg-vector-selector-benchmark/tsconfig.json
packages/pg-vector-selector/src/AgenticaPgVectorSelector.ts
packages/pg-vector-selector/src/Tools.ts
packages/pg-vector-selector/src/extract_query.ts
packages/pg-vector-selector/src/select.ts

plain:
plugin:
This pull request includes changes to the `AgenticaPgVectorSelector` to refactor query extraction and streamline the code. The most important changes include the addition of a new `extractQuery` function, removal of inline query extraction logic, and minor cleanup in the `BootAgenticaPgVectorSelector` function.
Refactoring and code cleanup:
* [`packages/pg-vector-selector/src/AgenticaPgVectorSelector.ts`](diffhunk://#diff-253fab8a8e7cdc9a558701d95d614c76132bbe5f7a642a47cfff07a5a02cd068L30-R38): Removed inline query extraction logic from the `BootAgenticaPgVectorSelector` function and replaced it with a call to the new `extractQuery` function. [[1]](diffhunk://#diff-253fab8a8e7cdc9a558701d95d614c76132bbe5f7a642a47cfff07a5a02cd068L30-R38) …

feat(pg-vector-selector): enhance accuracy(plain: 68, plugin: 57)

---

packages/pg-vector-selector/package.json
packages/pg-vector-selector/src/AgenticaPgVectorSelectorBootProps.ts
packages/pg-vector-selector/src/Tools.ts
packages/pg-vector-selector/src/extract_query.ts
packages/pg-vector-selector/src/select.ts
pnpm-lock.yaml

This pull request introduces several updates to the `pg-vector-selector` package, including dependency updates, feature enhancements, and code refactoring. Key changes include adding a new dependency (`json-schema-to-ts`), improving query extraction logic, and refining the structure of tool function parameters.
* Added `json-schema-to-ts` as a new dependency in `package.json` and updated `pnpm-lock.yaml` to include its resolution and dependencies. This library is used for type-safe JSON schema transformations. [[1]](diffhunk://#diff-17c97c54e8f9e9e170b125f77d0288d568fcbc648384108b88347b62b6f5e09fR59) [[2]](diffhunk://#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbR419-R421) [[3]](diffhunk://#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbR4984-R …

feat(benchmark): enhance accuracy

---

packages/pg-vector-selector/src/extract_query.ts
packages/pg-vector-selector/src/select.ts

before:
after: 
plain:
---
This pull request includes updates to improve the behavior and clarity of the query extraction and function selection processes in the `pg-vector-selector` package. The changes focus on refining system prompts, enhancing query extraction logic, and improving function selection guidelines.
* [`packages/pg-vector-selector/src/extract_query.ts`](diffhunk://#diff-494c13e2d5fdedf6c54e278f41f7d990d294b3c7eb3aee288882ed27e43c966bR8-R20): Updated the system prompt in the `extractQuery` function to clarify the role of the system and enforce extracting only one query per task. Added a new import for `reportStorage`, though its usage is not yet implemented.
* [`packages/pg-vector-selector/src/select.ts`](diffhunk://#diff-5ca4ab67fb780124ed645d52d817d0cc7dec51eea30a1b0b1d9ad …

chore(pg-vector-selector): enhance accurancy

---

README.md

This pull request includes a small update to the `README.md` file. A comment (``) was added above the TypeScript code block to disable ESLint for that section.

fix: lint on readme renewal

---

packages/core/src/factory/histories.ts

This pull request refactors the `decodeHistory` and `decodeUserMessageContent` functions in `packages/core/src/factory/histories.ts` to improve type safety and error handling. Key changes include replacing `else if` statements with separate `if` blocks, adding exhaustive type checks, and throwing errors for unsupported types.
* [`decodeHistory`](diffhunk://#diff-ffe98c9ddc17323da206ab3ec9a5bdea5eb03d9f302326fe024aff5f312120e9L94-R126): Replaced `else if` statements with standalone `if` blocks, added an exhaustive type check using `satisfies never`, and introduced an error for unsupported `history` types.
* [`decodeUserMessageContent`](diffhunk://#diff-ffe98c9ddc17323da206ab3ec9a5bdea5eb03d9f302326fe024aff5f312120e9L123-R137): Updated the function to use individual `if` blocks instead of …

fix: add type exhausted test(#426)

---

packages/chat/src/examples/shopping/ShoppingChatApplication.tsx
packages/chat/src/examples/shopping/index.tsx

Refactors ShoppingChatApplication to use React Suspense for asynchronous data loading. This improves the user experience by displaying a skeleton loader while the chat agent initializes.
The agent creation logic is now encapsulated within an async function, and the `AsyncAgenticaChatApplication` component utilizes the `use` hook to handle the promise. The parent component no longer needs to manage the Suspense boundary for this specific component.

 feat(website): apply react.use for ShoppingChat and stop using async component

---

README.md

This pull request updates the `README.md` file to enhance documentation and clarify the advantages of Agentica's function-calling capabilities. The changes include adding more detailed links to resources and tutorials, as well as updating the narrative to emphasize Agentica's role in resolving challenges in function-driven AI development.
* Expanded the list of resource links under "Guide Documents" to include sections on setup, concepts, core library, WebSocket protocol, and plugin modules.
* Added specific tutorial links for productivity, coding, React Native, and enterprise use cases under the "Tutorial" section.
* Updated the narrative to highlight how Agentica addresses the challenges of function calling, positioning it as a solution for returning to function-driven AI development.

Detailing README documentation chatper (requested by PMs)

---

packages/core/src/Agentica.ts
packages/core/src/MicroAgentica.ts
packages/core/src/context/AgenticaTokenUsage.ts
packages/core/src/structures/IAgenticaProps.ts
packages/core/src/structures/IMicroAgenticaProps.ts

This pull request introduces enhancements to token usage handling across the `Agentica` and `MicroAgentica` classes, as well as updates to related interfaces and utilities. The changes add support for initializing and tracking token usage through the `AgenticaTokenUsage` class and its JSON representation, enabling more flexible and traceable usage management.
* **Initialization of Token Usage in `Agentica` and `MicroAgentica` Classes**:
- Updated the `token_usage_` property to allow initialization from `AgenticaTokenUsage` instances or their JSON representations, providing flexibility in how token usage is set up. (`packages/core/src/Agentica.ts`, [[1]](diffhunk://#diff-fd17ccaf3913505148ef799667fe621b8664f52622f44959be527d79c5109898L97-R101); `packages/core/src/MicroAgentica.ts`, …

feat(core): token usage binding

---

packages/core/src/orchestrate/call.ts
packages/core/src/orchestrate/cancel.ts
packages/core/src/orchestrate/select.ts

This pull request refactors several functions in the `orchestrate` module to improve code readability and update the handling of tools and tool choices. The most significant changes include modifying the structure of tool definitions, updating the `tool_choice` logic, and improving the formatting of function signatures for better readability.
* Updated the `tool_choice` property in `correct`, `cancel`, and `select` functions to support conditional logic based on retry attempts. This ensures more precise tool selection during execution. (`packages/core/src/orchestrate/call.ts`: [[1]](diffhunk://#diff-fab757df7c77323a0efe9872a53054b76585edada69dc8515773aa7b598a023eL543-R546) `packages/core/src/orchestrate/cancel.ts`: [[2]](diffhunk://#diff-a2469a545a85656142890c66fc2867323de7a65a8685e7f144a4 …

feat(core): force function calling in validation feedback process

---

packages/core/prompts/execute.md
packages/core/prompts/validate.md

This pull request revises the `packages/core/prompts/execute.md` file to strengthen schema compliance rules and emphasize the importance of precise function argument construction. The changes introduce stricter guidelines for ensuring that all properties used in function calls are explicitly defined in the JSON schema, with zero tolerance for omissions or inventions. These updates aim to prevent validation errors and improve the reliability of AI function calls.
* **Critical Rule Enforcement**: Added explicit rules and examples to ensure properties used in function calls are strictly derived from the JSON schema, forbidding the creation of non-existent properties.
* **Property Verification Checklist**: Introduced a step-by-step checklist for verifying property existence against the schema …

feat(agent): enhance validate prompt

---

packages/chat/src/AgenticaChatApplication.tsx
packages/chat/src/examples/bbs/BbsChatApplication.tsx
packages/chat/src/examples/common/VendorConfigurationMovie.tsx
packages/chat/src/movies/AgenticaChatMovie.tsx
packages/chat/src/movies/sides/AgenticaChatSideMovie.tsx
packages/core/src/orchestrate/call.ts
packages/core/src/orchestrate/cancel.ts
packages/core/src/orchestrate/select.ts

This pull request introduces support for the `MicroAgentica` class alongside `Agentica`, updates the orchestration logic for tool selection, and refines the user interface for chat applications. Below are the most significant changes grouped by theme:
* Updated `AgenticaChatApplication` and `AgenticaChatMovie` components to accept both `Agentica` and `MicroAgentica` as valid agents. This includes changes to their props and event handling logic. (`[[1]](diffhunk://#diff-4b228842a876f7e32e9bbb583b050ead9b2e0a4a79fb4d52d67c68db504edf57L1-R1)`, `[[2]](diffhunk://#diff-4b228842a876f7e32e9bbb583b050ead9b2e0a4a79fb4d52d67c68db504edf57L11-R11)`, `[[3]](diffhunk://#diff-36e4cfdf39ba62466600231cde9f36e7ea1723fd1b39aab8e6915d255c3ed45fR106-R137)`, …

feat(core): `tool_choice` to be local LLM compatible.

---

packages/core/src/orchestrate/call.ts
packages/core/src/orchestrate/select.ts
packages/core/src/utils/AssistantMessageEmptyError.ts
packages/core/src/utils/ChatGptCompletionMessageUtil.ts
packages/core/src/utils/ChatGptCompletionStreamingUtil.ts
packages/core/src/utils/__retry.spec.ts
packages/core/src/utils/__retry.ts
test/src/features/rpc/test_rpc_websocket_call.ts

- Added __get_retry utility for retrying function calls with error handling.
- Introduced AssistantMessageEmptyError to manage cases of empty assistant messages.
- Updated call and select functions to utilize the new retry mechanism and handle empty messages appropriately.
- Enhanced streaming context management in both functions.
---
This pull request introduces a robust retry mechanism for handling transient failures in API calls, improves error handling for empty assistant messages, and adds comprehensive unit tests for the new retry logic. The changes also include minor code cleanup and type improvements for better maintainability and reliability.
* Added a generic `__get_retry` utility function to provide configurable retry logic for async operations, including propagation of …

feat(core): implement retry mechanism and handle empty assistant messages in orchestrate functions
